// GENERATED by scripts/extract-parts.mjs — do not edit by hand.
// Model facts only. Display labels (Furniture.labels) and tool (per action) live elsewhere.
import { PartDef, PartId, RawPartDef } from "@/src/game/core/type";

// Raw plain-string literal — validated by `satisfies`, then branded once below.
const PARTS_RAW = {
  "left": {"partId":"left","group":"left","meshName":"drawer01_left_small_front_bottom_screw_115339_center_pozi_slot_b","type":"structural","cluster":"drawer01","attached":["front_bottom_screw_115339_center_pozi_slot_b"],"visualCenterOffset":[-0.1905,0.115,1.0541],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "right": {"partId":"right","group":"right","meshName":"drawer01_right_small_front_bottom_screw_115339_center_pozi_slot_b","type":"structural","cluster":"drawer01","attached":["front_bottom_screw_115339_center_pozi_slot_b"],"visualCenterOffset":[0.1905,0.115,1.0541],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "top": {"partId":"top","group":"top","meshName":"carcass_top_panel","type":"structural","cluster":"carcass","visualCenterOffset":[0,0,1.221],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "bottom": {"partId":"bottom","group":"bottom","meshName":"carcass_bottom_panel","type":"structural","cluster":"carcass","visualCenterOffset":[0,0,0.009],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "back": {"partId":"back","group":"back","meshName":"carcass_back_hardboard_panel_110121","type":"structural","cluster":"carcass","attached":["panel_110121"],"visualCenterOffset":[0,0.237,0.615],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "front": {"partId":"front","group":"front","meshName":"carcass_front_bottom_plinth","type":"structural","cluster":"carcass","attached":["plinth"],"visualCenterOffset":[0,-0.246,0.04],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "rear": {"partId":"rear","group":"rear","meshName":"carcass_rear_bottom_plinth","type":"structural","cluster":"carcass","attached":["plinth"],"visualCenterOffset":[0,0.228,0.04],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "drawer": {"partId":"drawer","group":"drawer","meshName":"top_drawer_center_divider","type":"structural","cluster":"top","attached":["divider"],"visualCenterOffset":[0,-0.02,1.085],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "horizontal": {"partId":"horizontal","group":"horizontal","meshName":"rear_horizontal_stretcher_4","type":"structural","cluster":"rear","attached":["4"],"visualCenterOffset":[0,0.21,0.305],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "wide": {"partId":"wide","group":"wide","meshName":"drawer06_wide_front_bottom_screw_115339_center_pozi_slot_b","type":"structural","cluster":"drawer06","attached":["bottom_screw_115339_center_pozi_slot_b"],"visualCenterOffset":[0,0.115,0.1281],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "small": {"partId":"small","group":"small","meshName":"drawer02_small_box_right_front_wheel_axle","type":"structural","cluster":"drawer02","attached":["right_front_wheel_axle"],"visualCenterOffset":[0.371,-0.2136,1.08176],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "row1": {"partId":"row1","group":"row1","meshName":"carcass_row1_right_fixed_slider_front_wheel_axle","type":"structural","cluster":"carcass","attached":["fixed_slider_front_wheel_axle"],"visualCenterOffset":[0.386,-0.1836,1.105],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "row2": {"partId":"row2","group":"row2","meshName":"carcass_row2_right_fixed_slider_front_wheel_axle","type":"structural","cluster":"carcass","attached":["fixed_slider_front_wheel_axle"],"visualCenterOffset":[0.386,-0.1836,0.895],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "row3": {"partId":"row3","group":"row3","meshName":"carcass_row3_right_fixed_slider_front_wheel_axle","type":"structural","cluster":"carcass","attached":["fixed_slider_front_wheel_axle"],"visualCenterOffset":[0.386,-0.1836,0.665],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "row4": {"partId":"row4","group":"row4","meshName":"carcass_row4_right_fixed_slider_front_wheel_axle","type":"structural","cluster":"carcass","attached":["fixed_slider_front_wheel_axle"],"visualCenterOffset":[0.386,-0.1836,0.435],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "row5": {"partId":"row5","group":"row5","meshName":"carcass_row5_right_fixed_slider_front_wheel_axle","type":"structural","cluster":"carcass","attached":["fixed_slider_front_wheel_axle"],"visualCenterOffset":[0.386,-0.1836,0.205],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "side": {"partId":"side","group":"side","meshName":"right_side_dowel_101345_row5_rear_grip_ring_5","type":"structural","cluster":"right","attached":["101345_row5_rear_grip_ring_5"],"visualCenterOffset":[0.409303,0.175,0.205],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "panel": {"partId":"panel","group":"panel","meshName":"back_panel_nail_110121_bottom_4_pozi_slot_b","type":"structural","cluster":"back","attached":["110121_bottom_4_pozi_slot_b"],"visualCenterOffset":[0.305,0.2565,0.085],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "rail": {"partId":"rail","group":"rail","meshName":"front_rail_white_spacer_153548_158568_6","type":"structural","cluster":"front","attached":["spacer_153548_158568_6"],"visualCenterOffset":[0.3,-0.266,0.075],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
  "tip": {"partId":"tip","group":"tip","meshName":"anti_tip_right_cabinet_screw_recess","type":"structural","cluster":"anti","attached":["cabinet_screw_recess"],"visualCenterOffset":[0.363,0.244,1.122],"pose":{"position":[0,0,0],"rotation":[0,0,0,1]}},
} satisfies Record<string, Omit<RawPartDef, "tool">>;

export const PARTS = PARTS_RAW as unknown as Record<PartId, PartDef>;
export const ALL_PART_IDS = Object.keys(PARTS_RAW) as PartId[];
