// Where each assembly step's recording lives in storage.
//
// THE NUMBER IS THE LINE NUMBER. The clips were cut from the generated script (one text file, all
// four models at both text levels), and each file is named for the line it came from — so
// `LACK-standard-11.mp3` is line 11 of that file, which is the first LACK standard instruction.
//
// That is why the numbers do not start at 1 and why they are not action indices. LACK has thirteen
// actions but only four distinct sentences, because "Place the Leg into position." is said for every
// leg; the script lists each sentence ONCE, so there are four clips and one of them plays four
// times.
//
// The mapping is BY SENTENCE: format the step's instruction, find that line in its block, and its
// position gives the file. It used to be by position in the app's own deduped list, which is what
// broke — see the note on BLOCKS below for what that cost and why the two orderings differ.
import type { ActionId, Furniture, TextLevel } from "@/src/game/core/type";
import { buildInstructions, instructionText } from "@/src/game/core/presentation/instructions";

export const VOICEOVER_BUCKET = "Voiceover";

/**
 * Folder, file prefix, and THE BLOCK'S LINES IN SCRIPT ORDER.
 *
 * WHY THE LINES ARE HERE AS TEXT rather than a starting number and a count. The clip number used to
 * be `offset + the step's position in the app's deduped list`, which assumes the script was written
 * in the same order the app walks its actions. It was not. The generator grouped its output BY KIND
 * — every placement, then the cluster beats, then every fastener pair — while a build interleaves
 * them, fastening each sub-assembly as it goes.
 *
 * Both orderings contain the same sentences and the same number of them, which is exactly why the
 * bug survived: every offset was right, every count matched the uploaded files, and every wrong
 * number still resolved to a real clip. Nothing 404'd, nothing fell back to synthesis. The build
 * simply narrated a different step from the one on screen.
 *
 * LACK and BEKVAM were unaffected, and only by luck: their builds place every part before fastening
 * anything, so the two orderings coincide. DALFRED diverged at its first screw (15 of 20 standard
 * lines wrong, 9 of 14 simple) and EKET at its first runner screw (22 of 44, and 16 of 35).
 *
 * So a clip number is now a property of THE SENTENCE, not of the step's position: find the line in
 * this list, and its index from `firstLine` is the file. That also removes the older failure mode —
 * re-wording one step used to shift every clip after it, silently. Now an edited sentence simply
 * stops matching, and `stepVoicePath` returns null so the step falls back to synthesis instead of
 * confidently speaking its neighbour. stepVoice.test.ts turns that into a failure at build time.
 *
 * THE TEXT IS THE APP'S OWN, not retyped from the script. Each block was generated by running the
 * instruction builder and re-sorting its output into the script's order, then checked to be a
 * permutation of it — same set, no duplicates. Verified against the live bucket on 24 Aug: all eight
 * blocks' first and last files return 200 and the numbers either side return 400, and all 113 files
 * across the four models are present.
 *
 * FOLDER AND PREFIX ARE SPELLED OUT, because storage is case-sensitive and the uploads follow no
 * single rule: LACK's folder is capitalised where the others are lowercase, its two blocks disagree
 * with each other ("LACK-standard-11.mp3" but "LACK-Simple-17.mp3"), and DALFRED is spelled
 * "dalferd". A derived path would produce the name the code thinks is right and get silence.
 */
/** Exported for stepVoice.test.ts, which checks each step against the sentence its clip records. */
export const SCRIPT_BLOCKS: Record<
  string,
  Record<TextLevel, { folder: string; prefix: string; firstLine: number; lines: readonly string[] }> | undefined
> = {
  "lack-table": {
    standard: {
      folder: "LACK-Standard",
      prefix: "LACK-standard",
      firstLine: 11,
      lines: [
        /* 11 */ "Place the Table top into position.",
        /* 12 */ "Place the Leg into position.",
        /* 13 */ "Push the Bolt into its hole by hand.",
        /* 14 */ "Tighten the Bolt by hand.",
      ],
    },
    simple: {
      folder: "LACK-Simple",
      prefix: "LACK-Simple",
      firstLine: 17,
      lines: [
        /* 17 */ "Add the Top.",
        /* 18 */ "Add the Leg.",
        /* 19 */ "Start the Bolt by hand.",
        /* 20 */ "Tighten the Bolt.",
      ],
    },
  },
  "dalfred-stool": {
    standard: {
      folder: "dalferd-standard",
      prefix: "dalferd-standard",
      firstLine: 68,
      lines: [
        /* 68 */ "Place the Top plate into position.",
        /* 69 */ "Place the Leg into position.",
        /* 70 */ "Place the Bottom plate into position.",
        /* 71 */ "Place the Ring rail into position.",
        /* 72 */ "Place the Support pin into position.",
        /* 73 */ "Place the Seat into position.",
        /* 74 */ "Place the Seat plate into position.",
        /* 75 */ "Place the Pole into position.",
        /* 76 */ "Set the base down in place.",
        /* 77 */ "Set the seat's pole into the base and screw it clockwise until it sits tight.",
        /* 78 */ "Push the Wood screw into its hole by hand.",
        /* 79 */ "Tighten the Wood screw with the allen key.",
        /* 80 */ "Push the Ring rail screw into its hole by hand.",
        /* 81 */ "Tighten the Ring rail screw with the allen key.",
        /* 82 */ "Push the Support pin screw into its hole by hand.",
        /* 83 */ "Tighten the Support pin screw with the screwdriver.",
        /* 84 */ "Push the Plate screw into its hole by hand.",
        /* 85 */ "Tighten the Plate screw with the screwdriver.",
        /* 86 */ "Push the Cap into its hole by hand.",
        /* 87 */ "Tap the Cap fully in with the mallet.",
      ],
    },
    simple: {
      folder: "dalferd-simple",
      prefix: "dalferd-simple",
      firstLine: 90,
      lines: [
        /* 90 */ "Add the Top circle.",
        /* 91 */ "Add the Leg.",
        /* 92 */ "Add the Bottom circle.",
        /* 93 */ "Add the Round bar.",
        /* 94 */ "Add the Center pin.",
        /* 95 */ "Add the Seat.",
        /* 96 */ "Add the Plate.",
        /* 97 */ "Add the Pole.",
        /* 98 */ "Place the base.",
        /* 99 */ "Screw the seat onto the base.",
        /* 100 */ "Start the Screw by hand.",
        /* 101 */ "Tighten the Screw.",
        /* 102 */ "Start the Cap by hand.",
        /* 103 */ "Tap the Cap in.",
      ],
    },
  },
  "bekvam-stool": {
    standard: {
      folder: "bekvam-standard",
      prefix: "bekvam-standard",
      firstLine: 241,
      lines: [
        /* 241 */ "Place the Left side panel into position.",
        /* 242 */ "Place the Lower step into position.",
        /* 243 */ "Place the Right side panel into position.",
        /* 244 */ "Place the Back bottom rail into position.",
        /* 245 */ "Place the Front step rail into position.",
        /* 246 */ "Place the Front top rail into position.",
        /* 247 */ "Place the Back top rail into position.",
        /* 248 */ "Place the Top step into position.",
        /* 249 */ "Push the Wood dowel into its hole by hand.",
        /* 250 */ "Tap the Wood dowel fully in by hand.",
        /* 251 */ "Push the Wood screw into its hole by hand.",
        /* 252 */ "Tighten the Wood screw with the allen key.",
        /* 253 */ "Push the Long screw into its hole by hand.",
        /* 254 */ "Tighten the Long screw with the allen key.",
      ],
    },
    simple: {
      folder: "bekvam-simple",
      prefix: "bekvam-simple",
      firstLine: 257,
      lines: [
        /* 257 */ "Add the Left side.",
        /* 258 */ "Add the Step.",
        /* 259 */ "Add the Right side.",
        /* 260 */ "Add the Rail.",
        /* 261 */ "Add the Top.",
        /* 262 */ "Start the Peg by hand.",
        /* 263 */ "Tap the Peg in.",
        /* 264 */ "Start the Screw by hand.",
        /* 265 */ "Tighten the Screw.",
      ],
    },
  },
  "eket-cabinet": {
    standard: {
      folder: "eket-standard",
      prefix: "eket-standard",
      firstLine: 377,
      lines: [
        /* 377 */ "Place the Left side panel into position.",
        /* 378 */ "Place the Left runner into position.",
        /* 379 */ "Place the Left middle rail into position.",
        /* 380 */ "Place the Left slide into position.",
        /* 381 */ "Place the Slide clip into position.",
        /* 382 */ "Press the Top panel onto its pins, then push it forward to lock.",
        /* 383 */ "Press the Right side panel onto its pins, then push it back to lock.",
        /* 384 */ "Place the Right runner into position.",
        /* 385 */ "Place the Right middle rail into position.",
        /* 386 */ "Place the Right slide into position.",
        /* 387 */ "Place the Back panel into position.",
        /* 388 */ "Press the Bottom panel onto its pins, then push it forward to lock.",
        /* 389 */ "Take out the Stabiliser rod and set it down in front of you — you will fit its hardware before it goes in.",
        /* 390 */ "Set the Dowel at the end of the Stabiliser rod.",
        /* 391 */ "Press the Dowel into the end of the Stabiliser rod.",
        /* 392 */ "Pick the assembled Stabiliser rod back up and fit it into position.",
        /* 393 */ "Draw the Dowel out into the slider, then turn it a quarter turn to lock.",
        /* 394 */ "Place the Suspension bracket into position.",
        /* 395 */ "Tighten the Suspension bracket with the screwdriver.",
        /* 396 */ "Place the Adjuster knob into position.",
        /* 397 */ "Place the Suspension cover into position.",
        /* 398 */ "Place the Cover cap into position.",
        /* 399 */ "Place the Left drawer side into position.",
        /* 400 */ "Press the Drawer front onto its pins, then push it down to lock.",
        /* 401 */ "Press the Right drawer side onto its pins, then push it up to lock.",
        /* 402 */ "Place the Drawer bottom into position.",
        /* 403 */ "Place the Drawer back into position.",
        /* 404 */ "Place the Left runner bracket into position.",
        /* 405 */ "Place the Right runner bracket into position.",
        /* 406 */ "Stand the cabinet where it will live and settle it into place.",
        /* 407 */ "Line the top drawer up with the upper runners and slide it in until it clicks.",
        /* 408 */ "Slide the bottom drawer onto the lower runners the same way.",
        /* 409 */ "Press the front of the top drawer so it springs open, pull it all the way out, then push it home until it clicks.",
        /* 410 */ "Now the bottom drawer: press to pop it open, pull it out, and push it home.",
        /* 411 */ "Push the Back screw into its hole by hand.",
        /* 412 */ "Tighten the Back screw with the screwdriver.",
        /* 413 */ "Push the Bracket screw into its hole by hand.",
        /* 414 */ "Tighten the Bracket screw with the screwdriver.",
        /* 415 */ "Push the Runner screw into its hole by hand.",
        /* 416 */ "Tighten the Runner screw with the screwdriver.",
        /* 417 */ "Push the Cam lock into its hole by hand.",
        /* 418 */ "Press the Cam lock in until it seats.",
        /* 419 */ "Push the Cam pin into its hole by hand.",
        /* 420 */ "Press the Cam pin in until it seats.",
      ],
    },
    simple: {
      folder: "eket-simple",
      prefix: "eket-simple",
      firstLine: 423,
      lines: [
        /* 423 */ "Add the Left side.",
        /* 424 */ "Add the Runner.",
        /* 425 */ "Add the Middle.",
        /* 426 */ "Add the Slide.",
        /* 427 */ "Add the Clip.",
        /* 428 */ "Press the Top panel on, then push forward.",
        /* 429 */ "Press the Right side on, then push back.",
        /* 430 */ "Add the Back panel.",
        /* 431 */ "Press the Bottom panel on, then push forward.",
        /* 432 */ "Take out the Rod.",
        /* 433 */ "Add the Peg.",
        /* 434 */ "Press the Peg in.",
        /* 435 */ "Put the Rod in.",
        /* 436 */ "Pull the Peg out and turn to lock.",
        /* 437 */ "Add the Wall bracket.",
        /* 438 */ "Tighten the Wall bracket.",
        /* 439 */ "Add the Knob.",
        /* 440 */ "Add the Cover.",
        /* 441 */ "Add the Cap.",
        /* 442 */ "Press the Front on, then push down.",
        /* 443 */ "Press the Right side on, then push up.",
        /* 444 */ "Add the Base.",
        /* 445 */ "Add the Back.",
        /* 446 */ "Add the Bracket.",
        /* 447 */ "Put the cabinet in place.",
        /* 448 */ "Slide the top drawer in.",
        /* 449 */ "Slide the bottom drawer in.",
        /* 450 */ "Press the top drawer, pull it out, push it back in.",
        /* 451 */ "Press the bottom drawer, pull it out, push it back in.",
        /* 452 */ "Start the Screw by hand.",
        /* 453 */ "Tighten the Screw.",
        /* 454 */ "Start the Lock by hand.",
        /* 455 */ "Press the Lock in.",
        /* 456 */ "Start the Pin by hand.",
        /* 457 */ "Press the Pin in.",
      ],
    },
  },
};

/** Each action's instruction text. Cached: it walks every action and formats every instruction,
 *  which is wasted work to repeat on each spoken step.
 *
 *  It used to return a POSITION — the step's index in the deduped list — which is what tied the clip
 *  number to the app's action order. The text is what the recording is actually keyed on, so that is
 *  what this hands back now; BLOCKS does the numbering. */
//  KEYED ON THE FURNITURE OBJECT, not on its id. A `${id}:${level}` key meant two Furniture values
//  sharing an id shared one map — harmless in the app, where a model is loaded once, and a trap
//  anywhere a second one exists: a test standing up a small fixture under a real id would poison the
//  cache for the real content, and the real content would then report that half its steps have no
//  clip. A WeakMap also lets a swapped-out model be collected instead of pinning every furniture
//  ever loaded for the life of the process.
const lineCache = new WeakMap<Furniture, Map<TextLevel, Map<string, string>>>();

function lineTextFor(furniture: Furniture, level: TextLevel): Map<string, string> {
  let byLevel = lineCache.get(furniture);
  if (!byLevel) {
    byLevel = new Map();
    lineCache.set(furniture, byLevel);
  }
  const hit = byLevel.get(level);
  if (hit) return hit;

  const set = buildInstructions(
    furniture.actions,
    furniture.parts,
    furniture.labels,
    furniture.instructions ?? {},
    furniture.clusters ?? {},
  );
  // ACTION ORDER, first occurrence wins — the same walk the script did, so the positions agree.
  // No de-duplication step any more: repeated sentences simply map to the same text and therefore
  // to the same clip, which is what "Place the Leg into position." said four times always meant.
  const byAction = new Map<string, string>();
  for (const action of furniture.actions) {
    const text = instructionText(set, action.actionId, level);
    if (text) byAction.set(action.actionId, text);
  }
  byLevel.set(level, byAction);
  return byAction;
}

/**
 * The storage path for one step's recording, or null if there is no clip for it.
 *
 * Null covers a model with no recordings and an action that is not part of the build. Callers should
 * do what onboarding's speech does with a missing clip — fall back to synthesis rather than going
 * quiet, so a step is never silent just because a file is absent.
 */
export function stepVoicePath(
  furniture: Furniture,
  actionId: ActionId,
  level: TextLevel,
): string | null {
  const block = SCRIPT_BLOCKS[furniture.meta.id]?.[level];
  if (!block) return null;
  const text = lineTextFor(furniture, level).get(actionId);
  if (text === undefined) return null;
  // BY SENTENCE, not by position — see the note on BLOCKS. A step whose wording is no longer in the
  // block has no recording, and saying so is the point: the caller falls back to synthesis, which is
  // the honest outcome. Returning a neighbouring clip because it happens to sit at the same index is
  // the bug this replaced.
  const index = block.lines.indexOf(text);
  if (index < 0) return null;
  return `${block.folder}/${block.prefix}-${block.firstLine + index}.mp3`;
}