// GENERATED by src/game/helper-scripts/derive-joints.mts — do not edit by hand.
// Travel axes derived from the contact slabs at baked pose (core/model/jointGeometry.ts). Regenerate after any model re-export or JOINTS/STRUCTURE change; the derivedJoints pin test fails, named, when this file is stale.
// 8 derived, 4 undetermined:
//   circleUpp: contacts disagree and no travel is seated by more of them than any other — order-dependent, resolved at runtime, not here
//   pole: contacts disagree and no travel is seated by more of them than any other — order-dependent, resolved at runtime, not here
//   supportPin: no contact frame for the pair
//   supportPin: travels along Y through this contact, but the sign is not derivable — the partner surrounds the mover, so neither corridor objects
import type { JointGeometry } from "@/src/game/core/type";

export const JOINT_GEOMETRY = {
  "circleDown": {"placeDir":[0,1,0]},   // snap ↔ leg_1, normal, ext [0.05,0.04,0.05], sign: sweep-flipped
  "leg_1": {"placeDir":[0,0,1]},   // snap ↔ circleUpp, normal, ext [0.05,0.04,0.02], sign: toward-partner
  "leg_2": {"placeDir":[1,0,0]},   // snap ↔ circleUpp, normal, ext [0.03,0.04,0.05], sign: toward-partner
  "leg_3": {"placeDir":[0,0,-1]},   // snap ↔ circleUpp, normal, ext [0.05,0.04,0.02], sign: toward-partner
  "leg_4": {"placeDir":[-1,0,0]},   // snap ↔ circleUpp, normal, ext [0.03,0.04,0.05], sign: toward-partner
  "ringRail": {"placeDir":[0,1,0]},   // snap ↔ leg_3, normal, ext [0.05,0.04,0.13], sign: toward-partner
  "seat": {"placeDir":[0,-1,0]},   // snap ↔ seatPlate, normal, ext [0.17,0.04,0.17], sign: toward-partner
  "seatPlate": {"placeDir":[0,1,0]},   // snap ↔ seat, normal, ext [0.17,0.04,0.17], sign: toward-partner
} as JointGeometry;
