// GENERATED by src/game/helper-scripts/derive-structure.mts — do not edit by hand.
// Γ: the liaison graph core/model/liaisons.ts derives from the COMPOSED parts (structure.gen.ts spread over parts.gen.ts) — every joint the game knows about, with the mover and kind each one carries. The frontier, the build order, the joint frames and every blockReason read this.
// Nothing here is authored. An edge exists because a part names a join target or because a fastener names both endpoints, and its kind is either lowered from a JOINT or NAMED by the snap heuristic; the per-line notes say which.
// Regenerate after any JOINTS/FASTENERS/STRUCTURE change or model re-export; the liaisons pin test fails, named, when this file is stale.
// 16 edges: 1 press, 1 screw, 1 slide, 13 snap
import type { LiaisonMap } from "@/src/game/core/type";

export const LIAISONS = {
  "pole__seatPlate": {"id":"pole__seatPlate","a":"pole","b":"seatPlate","kind":"press"},
  "pole__supportPin": {"id":"pole__supportPin","a":"pole","b":"supportPin","kind":"screw","mover":"pole"},
  "circleUpp__supportPin": {"id":"circleUpp__supportPin","a":"circleUpp","b":"supportPin","kind":"slide","mover":"supportPin"},
  "leg_3__ringRail": {"id":"leg_3__ringRail","a":"leg_3","b":"ringRail","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "circleDown__leg_1": {"id":"circleDown__leg_1","a":"circleDown","b":"leg_1","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "seat__seatPlate": {"id":"seat__seatPlate","a":"seat","b":"seatPlate","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "circleDown__leg_2": {"id":"circleDown__leg_2","a":"circleDown","b":"leg_2","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "circleDown__leg_4": {"id":"circleDown__leg_4","a":"circleDown","b":"leg_4","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "circleDown__leg_3": {"id":"circleDown__leg_3","a":"circleDown","b":"leg_3","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "circleUpp__leg_3": {"id":"circleUpp__leg_3","a":"circleUpp","b":"leg_3","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "circleUpp__leg_2": {"id":"circleUpp__leg_2","a":"circleUpp","b":"leg_2","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "circleUpp__leg_1": {"id":"circleUpp__leg_1","a":"circleUpp","b":"leg_1","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "circleUpp__leg_4": {"id":"circleUpp__leg_4","a":"circleUpp","b":"leg_4","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "leg_1__ringRail": {"id":"leg_1__ringRail","a":"leg_1","b":"ringRail","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "leg_4__ringRail": {"id":"leg_4__ringRail","a":"leg_4","b":"ringRail","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "leg_2__ringRail": {"id":"leg_2__ringRail","a":"leg_2","b":"ringRail","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
} as unknown as LiaisonMap;
