// GENERATED by src/game/helper-scripts/derive-sweep.mts — do not edit by hand.
// Exit-sweep blockers per structural part per cardinal direction (see core/model/sweep.ts). Regenerate after any model re-export or STRUCTURE re-typing; the structuralSweep pin test fails, named, when this file is stale.
import type { SweepMap } from "@/src/game/core/type";

export const SWEEP = {
  "circleDown": {"+x":["leg_4","supportPin"],"-x":["leg_2","supportPin"],"+y":["circleUpp","leg_1","leg_2","leg_3","leg_4","supportPin"],"-y":["leg_2","leg_4","supportPin"],"+z":["leg_3","supportPin"],"-z":["leg_1","supportPin"]},
  "circleUpp": {"+x":["leg_4","supportPin"],"-x":["leg_2","supportPin"],"+y":["leg_1","leg_2","leg_4","supportPin"],"-y":["circleDown","leg_2"],"+z":["leg_3","supportPin"],"-z":["leg_1","supportPin"]},
  "leg_1": {"-y":["circleDown","circleUpp","ringRail"],"+z":["circleDown","circleUpp","ringRail","supportPin"]},
  "leg_2": {"+x":["circleDown","circleUpp","ringRail","supportPin"],"+y":["circleDown","ringRail"],"-y":["circleDown","circleUpp","ringRail"]},
  "leg_3": {"-y":["circleDown","ringRail"],"-z":["circleDown","circleUpp","ringRail","supportPin"]},
  "leg_4": {"-x":["circleDown","circleUpp","ringRail","supportPin"],"+y":["circleDown","ringRail"],"-y":["circleDown","circleUpp","ringRail"]},
  "pole": {"+x":["seatPlate"],"-x":["seatPlate"],"+y":["seat","seatPlate"],"+z":["seatPlate"],"-z":["seatPlate"]},
  "ringRail": {"+x":["leg_4"],"-x":["leg_2"],"+y":["leg_1","leg_2","leg_3","leg_4"],"+z":["leg_3"],"-z":["leg_1"]},
  "seat": {"+x":["seatPlate"],"-x":["seatPlate"],"+y":["seatPlate"],"-y":["pole","seatPlate"],"+z":["seatPlate"],"-z":["seatPlate"]},
  "seatPlate": {"+x":["pole","seat"],"-x":["pole","seat"],"+y":["seat"],"-y":["pole","seat"],"+z":["pole","seat"],"-z":["pole","seat"]},
  "supportPin": {"+x":["circleDown","circleUpp","leg_4"],"-x":["circleDown","circleUpp","leg_2"],"+y":["circleDown","circleUpp"],"-y":["circleDown","circleUpp"],"+z":["circleDown","circleUpp","leg_3"],"-z":["circleDown","circleUpp","leg_1"]},
} as SweepMap;
