// DRAFT authored.ts — GENERATED by scripts/extract-structure.mjs.
// Aims to SOLVE as-is: review every GUESS, then save as authored.ts.
//   derived: labels · clusters · rules+stages (Γ waves) · placements · directJoins
//   GUESSED (verify): seeds (footprint) · unstable (fastened-only) · stages ·
//     geometric trap requires · difficulty/duration
//   TODO (human): META catalogue facts · slide/screw join intent · beat overrides
import { FastenerRule } from "@/src/game/core/composition/composeActions";
import { StructureOverlay } from "@/src/game/core/model/liaisons";
import { DraftAction, ClusterDef, InstructionContent, LabelMap } from "@/src/game/core/type";

// 1 ─ META — name/brand/category/link are catalogue facts (TODO);
//     difficulty + duration are GUESSES from 160 estimated steps.
export const META = { name: "Eket", difficulty: 3 as const, duration: 65 };

// 2 ─ LABELS — STRUCTURAL groups only; TODO: improve wording.
//     (fastener labels come from data/hardware.ts — per-article, authored once)
export const LABELS: LabelMap = {
  backPanel: { standard: "Back panel" },
  suspBracket: { standard: "Susp bracket" },
  suspCover: { standard: "Susp cover" },
  suspCap: { standard: "Susp cap" },
  suspKnob: { standard: "Susp knob" },
  stabilizerRod: { standard: "Stabilizer rod" },
  runnerClip: { standard: "Runner clip" },
  runnerLatchR: { standard: "Runner latch r" },
  runnerRailR: { standard: "Runner rail r" },
  runnerRailL: { standard: "Runner rail l" },
  runnerLatchL: { standard: "Runner latch l" },
  runnerFixLA: { standard: "Runner fix la" },
  runnerMidL: { standard: "Runner mid l" },
  runnerInnerL: { standard: "Runner inner l" },
  runnerFixLB: { standard: "Runner fix lb" },
  runnerFixRA: { standard: "Runner fix ra" },
  runnerMidR: { standard: "Runner mid r" },
  runnerInnerR: { standard: "Runner inner r" },
  runnerFixRB: { standard: "Runner fix rb" },
  sidePanelL: { standard: "Side panel l" },
  topPanel: { standard: "Top panel" },
  bottomPanel: { standard: "Bottom panel" },
  sidePanelR: { standard: "Side panel r" },
  runnerBracketR: { standard: "Runner bracket r" },
  runnerBracketL: { standard: "Runner bracket l" },
  drawerBack: { standard: "Drawer back" },
  drawerSideR: { standard: "Drawer side r" },
  drawerSideL: { standard: "Drawer side l" },
  drawerBottom: { standard: "Drawer bottom" },
  drawerFront: { standard: "Drawer front" },
};

// 3 ─ CLUSTERS.
export const CLUSTERS: Record<string, ClusterDef> = {
  cabinet: { id: "cabinet", label: "Cabinet" },
  drawerA: { id: "drawerA", label: "Drawer a" },
  drawerB: { id: "drawerB", label: "Drawer b" },
};

// 4 ─ STRUCTURE — GUESSES to verify: seed = largest footprint per cluster;
//     unstable = held only by fasteners. directJoins = fastener-free contacts
//     only (fastened joints come from the mesh names).
export const STRUCTURE: StructureOverlay = {
  // ── cabinet ──  suggested order (verify!): runnerFixRB → runnerFixLB → runnerFixRA → runnerFixLA → suspKnob_2 → suspBracket_1 → suspKnob_1 → suspBracket_2 → suspCover_2 → suspCover_1 → suspCap_2 → suspCap_1 → backPanel → bottomPanel → sidePanelR → sidePanelL → topPanel
  runnerFixRB: { }, // GUESSED seed/unstable — verify
  runnerFixLB: { }, // GUESSED seed/unstable — verify
  runnerFixRA: { }, // GUESSED seed/unstable — verify
  runnerFixLA: { }, // GUESSED seed/unstable — verify
  suspKnob_2: { }, // GUESSED seed/unstable — verify
  suspBracket_1: { directJoins: ["suspKnob_2"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  suspKnob_1: { }, // GUESSED seed/unstable — verify
  suspBracket_2: { directJoins: ["suspKnob_1"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  suspCover_2: { directJoins: ["suspBracket_2"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  suspCover_1: { directJoins: ["suspBracket_1"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  suspCap_2: { directJoins: ["suspCover_2"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  suspCap_1: { directJoins: ["suspCover_1"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  backPanel: { unstable: true }, // GUESSED seed/unstable — verify
  bottomPanel: { }, // GUESSED seed/unstable — verify
  sidePanelR: { directJoins: ["suspBracket_1", "bottomPanel"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  sidePanelL: { directJoins: ["suspBracket_2", "bottomPanel"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  topPanel: { seed: true, directJoins: ["sidePanelL", "sidePanelR"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  // ── drawerA ──  suggested order (verify!): runnerLatchL_1 → runnerMidL_1 → runnerBracketR_1 → runnerClip_1 → runnerInnerL_1 → runnerRailL_1 → runnerLatchR_1 → runnerMidR_1 → runnerRailR_1 → runnerBracketL_1 → runnerClip_3 → runnerInnerR_1 → drawerBottom_1 → drawerSideL_1 → drawerSideR_1 → stabilizerRod_1 → drawerBack_1 → drawerFront_1
  runnerLatchL_1: { }, // GUESSED seed/unstable — verify
  runnerMidL_1: { directJoins: ["runnerLatchL_1"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  runnerBracketR_1: { }, // GUESSED seed/unstable — verify
  runnerClip_1: { }, // GUESSED seed/unstable — verify
  runnerInnerL_1: { directJoins: ["runnerClip_1", "runnerLatchL_1"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  runnerRailL_1: { directJoins: ["runnerFixLA"] }, // GUESSED seed/unstable — verify; directJoins is CROSS-CLUSTER → likely screwJoins + combine (see GAPS.json)
  runnerLatchR_1: { }, // GUESSED seed/unstable — verify
  runnerMidR_1: { directJoins: ["runnerLatchR_1"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  runnerRailR_1: { directJoins: ["runnerFixRA"] }, // GUESSED seed/unstable — verify; directJoins is CROSS-CLUSTER → likely screwJoins + combine (see GAPS.json)
  runnerBracketL_1: { }, // GUESSED seed/unstable — verify
  runnerClip_3: { }, // GUESSED seed/unstable — verify
  runnerInnerR_1: { directJoins: ["runnerClip_3", "runnerLatchR_1"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  drawerBottom_1: { seed: true }, // GUESSED seed/unstable — verify
  drawerSideL_1: { unstable: true }, // GUESSED seed/unstable — verify
  drawerSideR_1: { unstable: true }, // GUESSED seed/unstable — verify
  stabilizerRod_1: { }, // GUESSED seed/unstable — verify
  drawerBack_1: { unstable: true }, // GUESSED seed/unstable — verify
  drawerFront_1: { directJoins: ["runnerBracketR_1", "runnerBracketL_1"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  // ── drawerB ──  suggested order (verify!): runnerLatchL_2 → runnerMidL_2 → runnerBracketR_2 → runnerClip_2 → runnerInnerL_2 → runnerRailL_2 → runnerLatchR_2 → runnerMidR_2 → runnerRailR_2 → runnerBracketL_2 → runnerClip_4 → runnerInnerR_2 → drawerBottom_2 → drawerSideL_2 → drawerSideR_2 → stabilizerRod_2 → drawerBack_2 → drawerFront_2
  runnerLatchL_2: { }, // GUESSED seed/unstable — verify
  runnerMidL_2: { directJoins: ["runnerLatchL_2"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  runnerBracketR_2: { }, // GUESSED seed/unstable — verify
  runnerClip_2: { }, // GUESSED seed/unstable — verify
  runnerInnerL_2: { directJoins: ["runnerClip_2", "runnerLatchL_2"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  runnerRailL_2: { directJoins: ["runnerFixLB"] }, // GUESSED seed/unstable — verify; directJoins is CROSS-CLUSTER → likely screwJoins + combine (see GAPS.json)
  runnerLatchR_2: { }, // GUESSED seed/unstable — verify
  runnerMidR_2: { directJoins: ["runnerLatchR_2"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  runnerRailR_2: { directJoins: ["runnerFixRB"] }, // GUESSED seed/unstable — verify; directJoins is CROSS-CLUSTER → likely screwJoins + combine (see GAPS.json)
  runnerBracketL_2: { }, // GUESSED seed/unstable — verify
  runnerClip_4: { }, // GUESSED seed/unstable — verify
  runnerInnerR_2: { directJoins: ["runnerClip_4", "runnerLatchR_2"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
  drawerBottom_2: { seed: true }, // GUESSED seed/unstable — verify
  drawerSideL_2: { unstable: true }, // GUESSED seed/unstable — verify
  drawerSideR_2: { unstable: true }, // GUESSED seed/unstable — verify
  stabilizerRod_2: { }, // GUESSED seed/unstable — verify
  drawerBack_2: { unstable: true }, // GUESSED seed/unstable — verify
  drawerFront_2: { directJoins: ["runnerBracketR_2", "runnerBracketL_2"] }, // GUESSED seed/unstable — verify; directJoins = PRESS guess — press|slide|screw? (see GAPS.json)
};

// 5 ─ FASTENER_RULES — one per fastener group; stage DERIVED (the Γ wave
//     where the joint closes) — verify against the manual.
//     Everything else is derived: requires = the secured default (every
//     attached part placed first); tool/label/motion come from the GLOBAL
//     catalogue (data/hardware.ts) — one line there per UNSEEN article number.
export const FASTENER_RULES: FastenerRule[] = [
  { group: "cam139434", stage: 3 },
  { group: "dowel139435", stage: 3 },
  { group: "screw100349", stage: 3 },
  { group: "dowel145572", stage: 1 },
  { group: "screw109041", stage: 1 },
  { group: "screw110519", stage: 1 },
  { group: "bolt128918", stage: 1 },
];

// 6 ─ AUTHORED_ACTIONS — one placement per structural part. Ids derive from
//     (type, partId); stages are Γ waves; requires are GEOMETRIC traps (the
//     closing part waits for what it traps). Verify both against the manual.
//     Fastener insert/tighten expand from FASTENER_RULES.
export const AUTHORED_ACTIONS: DraftAction[] = [
  // ── cabinet ──
  { type: "placePart", stage: 3, partId: "runnerFixRB", requires: [] },
  { type: "placePart", stage: 3, partId: "runnerFixLB", requires: [] },
  { type: "placePart", stage: 3, partId: "runnerFixRA", requires: [] },
  { type: "placePart", stage: 3, partId: "runnerFixLA", requires: [] },
  { type: "placePart", stage: 4, partId: "suspKnob_2", requires: [] },
  { type: "placePart", stage: 3, partId: "suspBracket_1", requires: [] },
  { type: "placePart", stage: 4, partId: "suspKnob_1", requires: [] },
  { type: "placePart", stage: 3, partId: "suspBracket_2", requires: [] },
  { type: "placePart", stage: 4, partId: "suspCover_2", requires: [] },
  { type: "placePart", stage: 4, partId: "suspCover_1", requires: [] },
  { type: "placePart", stage: 5, partId: "suspCap_2", requires: [] },
  { type: "placePart", stage: 5, partId: "suspCap_1", requires: [] },
  { type: "placePart", stage: 2, partId: "backPanel", requires: [] },
  { type: "placePart", stage: 3, partId: "bottomPanel", requires: [] },
  { type: "placePart", stage: 2, partId: "sidePanelR", requires: [] },
  { type: "placePart", stage: 2, partId: "sidePanelL", requires: [] },
  { type: "placePart", stage: 1, partId: "topPanel", requires: [] },
  // ── drawerA ──
  { type: "placePart", stage: 1, partId: "runnerLatchL_1", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerMidL_1", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerBracketR_1", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerClip_1", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerInnerL_1", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerRailL_1", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerLatchR_1", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerMidR_1", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerRailR_1", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerBracketL_1", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerClip_3", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerInnerR_1", requires: [] },
  { type: "placePart", stage: 1, partId: "drawerBottom_1", requires: [] },
  { type: "placePart", stage: 1, partId: "drawerSideL_1", requires: [] },
  { type: "placePart", stage: 1, partId: "drawerSideR_1", requires: [] },
  { type: "placePart", stage: 1, partId: "stabilizerRod_1", requires: [] },
  { type: "placePart", stage: 1, partId: "drawerBack_1", requires: [] },
  { type: "placePart", stage: 1, partId: "drawerFront_1", requires: [] },
  // ── drawerB ──
  { type: "placePart", stage: 1, partId: "runnerLatchL_2", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerMidL_2", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerBracketR_2", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerClip_2", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerInnerL_2", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerRailL_2", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerLatchR_2", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerMidR_2", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerRailR_2", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerBracketL_2", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerClip_4", requires: [] },
  { type: "placePart", stage: 1, partId: "runnerInnerR_2", requires: [] },
  { type: "placePart", stage: 1, partId: "drawerBottom_2", requires: [] },
  { type: "placePart", stage: 1, partId: "drawerSideL_2", requires: [] },
  { type: "placePart", stage: 1, partId: "drawerSideR_2", requires: [] },
  { type: "placePart", stage: 1, partId: "stabilizerRod_2", requires: [] },
  { type: "placePart", stage: 1, partId: "drawerBack_2", requires: [] },
  { type: "placePart", stage: 1, partId: "drawerFront_2", requires: [] },
  // TODO combine: combineReady waits for every cluster to finish.
  { actionId: "combine_assemblies", type: "combineClusters", stage: 5, cluster: "drawerB", requires: [] },
  // TODO: add reorient/combine beats (a clustered reorient waits for its cluster to finish).
  { actionId: "finishing_checks", type: "reorient", stage: 5, requires: [] },
];

// 7 ─ BEATS — OPTIONAL overrides. Part-less beats auto-word from the
//     cluster labels (buildInstructions defaults); add an entry ONLY where
//     the generic wording isn't good enough.
export const BEATS: Record<string, InstructionContent> = {};
