// GENERATED by scripts/gen-thumbs.mjs - do not edit by hand.
// Run: npm run gen:thumbs

import type { ThumbMap, ThumbSet } from "@/src/game/core/type";

export const thumbnail = { light: require("../../../../assets/thumbnails/furnitures/LACK/light/LACK.png") } satisfies ThumbSet;

export const thumbs = {
  "bolt115980": { light: require("../../../../assets/thumbnails/furnitures/LACK/light/parts/whole_bolt115980.png") },
  "leg": { light: require("../../../../assets/thumbnails/furnitures/LACK/light/parts/whole_leg.png") },
  "tableTop": { light: require("../../../../assets/thumbnails/furnitures/LACK/light/parts/whole_tableTop.png") },
} as ThumbMap;
