// GENERATED by src/game/helper-scripts/derive-structure.mts — do not edit by hand.
// Travel axes derived from the contact slabs at baked pose (core/derive/jointGeometry.ts). Regenerate after any model re-export or JOINTS/STRUCTURE change; the derivedJoints pin test fails, named, when this file is stale.
// 30 derived, 15 undetermined:
//   bottomPanel: contacts disagree and no travel is seated by more of them than any other — order-dependent, resolved at runtime, not here
//   drawerSideL_1: contacts disagree and no travel is seated by more of them than any other — order-dependent, resolved at runtime, not here
//   drawerSideL_2: contacts disagree and no travel is seated by more of them than any other — order-dependent, resolved at runtime, not here
//   runnerCarriageL_1: both signs have third-party blockers in the exit corridor
//   runnerCarriageL_2: both signs have third-party blockers in the exit corridor
//   runnerCarriageR_1: both signs have third-party blockers in the exit corridor
//   runnerCarriageR_2: both signs have third-party blockers in the exit corridor
//   runnerClip_1: travels along X through this contact, but the sign is not derivable — the partner surrounds the mover, so neither corridor objects
//   runnerClip_2: travels along X through this contact, but the sign is not derivable — the partner surrounds the mover, so neither corridor objects
//   runnerClip_3: travels along X through this contact, but the sign is not derivable — the partner surrounds the mover, so neither corridor objects
//   runnerClip_4: travels along X through this contact, but the sign is not derivable — the partner surrounds the mover, so neither corridor objects
//   stabilizerRod_1: dowel145572_1 drives along this pair, but both signs have third-party blockers in the exit corridor
//   stabilizerRod_1: dowel145572_2 drives along this pair, but both signs have third-party blockers in the exit corridor
//   stabilizerRod_2: dowel145572_3 drives along this pair, but both signs have third-party blockers in the exit corridor
//   stabilizerRod_2: dowel145572_4 drives along this pair, but both signs have third-party blockers in the exit corridor
import type { JointGeometry } from "@/src/game/core/type";

export const JOINT_GEOMETRY = {
  "backPanel": {"placeDir":[0,1,0]},   // slide ↔ sidePanelL, slab-long, ext [0.02,0.35,0.03], sign: sweep
  "drawerBack_1": {"placeDir":[1,0,0]},   // snap ↔ drawerSideR_1, normal, ext [0.02,0.13,0.03], sign: toward-partner
  "drawerBack_2": {"placeDir":[1,0,0]},   // snap ↔ drawerSideR_2, normal, ext [0.02,0.13,0.03], sign: toward-partner
  "drawerBottom_1": {"placeDir":[1,0,0]},   // slide ↔ drawerSideL_1, slab-long, ext [0.3,0.02,0.03], sign: sweep
  "drawerBottom_2": {"placeDir":[1,0,0]},   // slide ↔ drawerSideL_2, slab-long, ext [0.3,0.02,0.03], sign: sweep
  "drawerFront_1": {"placeDir":[-1,0,0]},   // hookAndSlot ↔ drawerSideL_1, normal, ext [0.03,0.13,0.03], sign: toward-partner
  "drawerFront_2": {"placeDir":[-1,0,0]},   // hookAndSlot ↔ drawerSideL_2, normal, ext [0.03,0.13,0.03], sign: toward-partner
  "drawerSideR_1": {"placeDir":[1,0,0]},   // snap ↔ drawerFront_1, normal, ext [0.03,0.13,0.03], sign: toward-partner
  "drawerSideR_2": {"placeDir":[1,0,0]},   // snap ↔ drawerFront_2, normal, ext [0.03,0.13,0.03], sign: toward-partner
  "runnerBracketL_1": {"placeDir":[1,0,0]},   // snap ↔ drawerFront_1, normal, ext [0.02,0.04,0.08], sign: toward-partner
  "runnerBracketL_2": {"placeDir":[1,0,0]},   // snap ↔ drawerFront_2, normal, ext [0.02,0.04,0.08], sign: toward-partner
  "runnerBracketR_1": {"placeDir":[1,0,0]},   // snap ↔ drawerFront_1, normal, ext [0.02,0.04,0.07], sign: toward-partner
  "runnerBracketR_2": {"placeDir":[1,0,0]},   // snap ↔ drawerFront_2, normal, ext [0.02,0.04,0.07], sign: toward-partner
  "runnerFrameL_1": {"placeDir":[0,0,1]},   // snap ↔ sidePanelL, normal, ext [0.26,0.07,0.02], sign: toward-partner
  "runnerFrameL_2": {"placeDir":[0,0,1]},   // snap ↔ sidePanelL, normal, ext [0.26,0.07,0.02], sign: toward-partner
  "runnerFrameR_1": {"placeDir":[0,0,-1]},   // snap ↔ sidePanelR, normal, ext [0.26,0.07,0.02], sign: toward-partner
  "runnerFrameR_2": {"placeDir":[0,0,-1]},   // snap ↔ sidePanelR, normal, ext [0.26,0.07,0.02], sign: toward-partner
  "runnerMiddleL_1": {"placeDir":[0,1,0]},   // press ↔ runnerFrameL_1, normal, ext [0.18,0.04,0.04], sign: toward-partner
  "runnerMiddleL_2": {"placeDir":[0,1,0]},   // press ↔ runnerFrameL_2, normal, ext [0.18,0.04,0.04], sign: toward-partner
  "runnerMiddleR_1": {"placeDir":[0,1,0]},   // press ↔ runnerFrameR_1, normal, ext [0.18,0.04,0.04], sign: toward-partner
  "runnerMiddleR_2": {"placeDir":[0,1,0]},   // press ↔ runnerFrameR_2, normal, ext [0.18,0.04,0.04], sign: toward-partner
  "sidePanelL": {"placeDir":[0,0,-1]},   // hookAndSlot ↔ topPanel, normal, ext [0.37,0.04,0.03], sign: toward-partner
  "sidePanelR": {"placeDir":[0,0,1]},   // hookAndSlot ↔ topPanel, normal, ext [0.37,0.04,0.03], sign: toward-partner
  "suspBracket_1": {"placeDir":[0,0,-1]},   // press ↔ sidePanelR, normal, ext [0.04,0.06,0.03], sign: toward-partner
  "suspBracket_2": {"placeDir":[0,0,1]},   // press ↔ sidePanelL, normal, ext [0.03,0.06,0.03], sign: toward-partner
  "suspCover_1": {"placeDir":[-1,0,0]},   // snap ↔ suspBracket_1, normal, ext [0.02,0.04,0.04], sign: toward-partner
  "suspCover_2": {"placeDir":[-1,0,0]},   // snap ↔ suspBracket_2, normal, ext [0.02,0.04,0.04], sign: toward-partner
  "suspKnob_1": {"placeDir":[1,0,0]},   // screw ↔ suspBracket_2, normal, ext [0.03,0.05,0.05], sign: toward-partner
  "suspKnob_2": {"placeDir":[1,0,0]},   // screw ↔ suspBracket_1, normal, ext [0.03,0.05,0.05], sign: toward-partner
  "topPanel": {"placeDir":[0,0,1]},   // snap ↔ sidePanelL, normal, ext [0.37,0.04,0.03], sign: toward-partner
} as JointGeometry;
