// GENERATED by src/game/helper-scripts/derive-joints.mts — do not edit by hand.
// Travel axes derived from the contact slabs at baked pose (core/model/jointGeometry.ts). Regenerate after any model re-export or JOINTS/STRUCTURE change; the derivedJoints pin test fails, named, when this file is stale.
// 26 derived, 13 undetermined:
//   bottomPanel: several unblocked contacts claim different travel — order-dependent, resolved at runtime, not here
//   drawerBottom_1: both signs clear — the sweep cannot choose
//   drawerBottom_2: both signs clear — the sweep cannot choose
//   runnerCarriageL_1: both signs have third-party blockers in the exit corridor
//   runnerCarriageL_2: both signs have third-party blockers in the exit corridor
//   runnerCarriageR_1: both signs have third-party blockers in the exit corridor
//   runnerCarriageR_2: both signs have third-party blockers in the exit corridor
//   runnerClip_1: slab axes tied within 5mm (0.032 vs 0.030) — the ranking is rounding, not shape
//   runnerClip_2: slab axes tied within 5mm (0.032 vs 0.030) — the ranking is rounding, not shape
//   runnerClip_3: slab axes tied within 5mm (0.032 vs 0.030) — the ranking is rounding, not shape
//   runnerClip_4: slab axes tied within 5mm (0.032 vs 0.030) — the ranking is rounding, not shape
//   stabilizerRod_1: parts do not touch — a bridged liaison has a centre line, not a contact slab
//   stabilizerRod_2: parts do not touch — a bridged liaison has a centre line, not a contact slab
import type { JointGeometry } from "@/src/game/core/type";

export const JOINT_GEOMETRY = {
  "backPanel": {"placeDir":[0,1,0]},   // slide ↔ sidePanelL, slab-long, ext [0.02,0.35,0.03], sign: sweep
  "drawerBack_1": {"placeDir":[1,0,0]},   // snap ↔ drawerSideR_1, normal, ext [0.02,0.13,0.03], sign: toward-partner
  "drawerBack_2": {"placeDir":[1,0,0]},   // snap ↔ drawerSideR_2, normal, ext [0.02,0.13,0.03], sign: toward-partner
  "drawerFront_1": {"placeDir":[-1,0,0]},   // press ↔ drawerSideL_1, normal, ext [0.03,0.13,0.03], sign: toward-partner
  "drawerFront_2": {"placeDir":[-1,0,0]},   // press ↔ drawerSideL_2, normal, ext [0.03,0.13,0.03], sign: toward-partner
  "drawerSideL_1": {"placeDir":[1,0,0]},   // press ↔ drawerFront_1, normal, ext [0.03,0.13,0.03], sign: toward-partner
  "drawerSideL_2": {"placeDir":[1,0,0]},   // press ↔ drawerFront_2, normal, ext [0.03,0.13,0.03], sign: toward-partner
  "drawerSideR_1": {"placeDir":[1,0,0]},   // press ↔ drawerFront_1, normal, ext [0.03,0.13,0.03], sign: toward-partner
  "drawerSideR_2": {"placeDir":[1,0,0]},   // press ↔ drawerFront_2, normal, ext [0.03,0.13,0.03], sign: toward-partner
  "runnerBracketL_1": {"placeDir":[1,0,0]},   // snap ↔ drawerFront_1, normal, ext [0.02,0.04,0.08], sign: toward-partner
  "runnerBracketL_2": {"placeDir":[1,0,0]},   // snap ↔ drawerFront_2, normal, ext [0.02,0.04,0.08], sign: toward-partner
  "runnerBracketR_1": {"placeDir":[1,0,0]},   // snap ↔ drawerFront_1, normal, ext [0.02,0.04,0.07], sign: toward-partner
  "runnerBracketR_2": {"placeDir":[1,0,0]},   // snap ↔ drawerFront_2, normal, ext [0.02,0.04,0.07], sign: toward-partner
  "runnerFrameL_1": {"placeDir":[0,0,1]},   // snap ↔ sidePanelL, normal, ext [0.26,0.07,0.02], sign: toward-partner
  "runnerFrameL_2": {"placeDir":[0,0,1]},   // snap ↔ sidePanelL, normal, ext [0.26,0.07,0.02], sign: toward-partner
  "runnerFrameR_1": {"placeDir":[0,0,-1]},   // snap ↔ sidePanelR, normal, ext [0.26,0.07,0.02], sign: toward-partner
  "runnerFrameR_2": {"placeDir":[0,0,-1]},   // snap ↔ sidePanelR, normal, ext [0.26,0.07,0.02], sign: toward-partner
  "sidePanelL": {"placeDir":[0,0,-1]},   // press ↔ topPanel, normal, ext [0.37,0.04,0.03], sign: toward-partner
  "sidePanelR": {"placeDir":[0,0,1]},   // press ↔ topPanel, normal, ext [0.37,0.04,0.03], sign: toward-partner
  "suspBracket_1": {"placeDir":[0,0,-1]},   // press ↔ sidePanelR, normal, ext [0.04,0.06,0.03], sign: toward-partner
  "suspBracket_2": {"placeDir":[0,0,1]},   // press ↔ sidePanelL, normal, ext [0.03,0.06,0.03], sign: toward-partner
  "suspCover_1": {"placeDir":[-1,0,0]},   // press ↔ suspBracket_1, normal, ext [0.02,0.04,0.04], sign: toward-partner
  "suspCover_2": {"placeDir":[-1,0,0]},   // press ↔ suspBracket_2, normal, ext [0.02,0.04,0.04], sign: toward-partner
  "suspKnob_1": {"placeDir":[1,0,0]},   // screw ↔ suspBracket_2, normal, ext [0.03,0.05,0.05], sign: toward-partner
  "suspKnob_2": {"placeDir":[1,0,0]},   // screw ↔ suspBracket_1, normal, ext [0.03,0.05,0.05], sign: toward-partner
  "topPanel": {"placeDir":[0,0,1]},   // snap ↔ sidePanelL, normal, ext [0.37,0.04,0.03], sign: toward-partner
} as JointGeometry;
