// GENERATED by src/game/helper-scripts/derive-structure.mts — do not edit by hand.
// Γ: the liaison graph core/model/liaisons.ts derives from the COMPOSED parts (structure.gen.ts spread over parts.gen.ts) — every joint the game knows about, with the mover and kind each one carries. The frontier, the build order, the joint frames and every blockReason read this.
// Nothing here is authored. An edge exists because a part names a join target or because a fastener names both endpoints, and its kind is either lowered from a JOINT or NAMED by the snap heuristic; the per-line notes say which.
// Regenerate after any JOINTS/FASTENERS/STRUCTURE change or model re-export; the liaisons pin test fails, named, when this file is stale.
// 52 edges: 18 (unnamed), 20 press, 2 screw, 12 slide
import type { LiaisonMap } from "@/src/game/core/type";

export const LIAISONS = {
  "backPanel__sidePanelL": {"id":"backPanel__sidePanelL","a":"backPanel","b":"sidePanelL","kind":"slide","mover":"backPanel"},
  "backPanel__sidePanelR": {"id":"backPanel__sidePanelR","a":"backPanel","b":"sidePanelR","kind":"slide","mover":"backPanel"},
  "sidePanelR__suspBracket_1": {"id":"sidePanelR__suspBracket_1","a":"sidePanelR","b":"suspBracket_1","kind":"press"},
  "suspBracket_1__suspCover_1": {"id":"suspBracket_1__suspCover_1","a":"suspBracket_1","b":"suspCover_1","kind":"press"},
  "suspBracket_1__suspKnob_2": {"id":"suspBracket_1__suspKnob_2","a":"suspBracket_1","b":"suspKnob_2","kind":"screw","mover":"suspKnob_2"},
  "sidePanelL__suspBracket_2": {"id":"sidePanelL__suspBracket_2","a":"sidePanelL","b":"suspBracket_2","kind":"press"},
  "suspBracket_2__suspCover_2": {"id":"suspBracket_2__suspCover_2","a":"suspBracket_2","b":"suspCover_2","kind":"press"},
  "suspBracket_2__suspKnob_1": {"id":"suspBracket_2__suspKnob_1","a":"suspBracket_2","b":"suspKnob_1","kind":"screw","mover":"suspKnob_1"},
  "backPanel__bottomPanel": {"id":"backPanel__bottomPanel","a":"backPanel","b":"bottomPanel"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "backPanel__topPanel": {"id":"backPanel__topPanel","a":"backPanel","b":"topPanel"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "runnerFrameR_1__sidePanelR": {"id":"runnerFrameR_1__sidePanelR","a":"runnerFrameR_1","b":"sidePanelR"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "runnerFrameR_2__sidePanelR": {"id":"runnerFrameR_2__sidePanelR","a":"runnerFrameR_2","b":"sidePanelR"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "runnerFrameL_1__sidePanelL": {"id":"runnerFrameL_1__sidePanelL","a":"runnerFrameL_1","b":"sidePanelL"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "runnerFrameL_2__sidePanelL": {"id":"runnerFrameL_2__sidePanelL","a":"runnerFrameL_2","b":"sidePanelL"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "runnerFrameL_1__stabilizerRod_1": {"id":"runnerFrameL_1__stabilizerRod_1","a":"runnerFrameL_1","b":"stabilizerRod_1"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "runnerFrameR_1__stabilizerRod_1": {"id":"runnerFrameR_1__stabilizerRod_1","a":"runnerFrameR_1","b":"stabilizerRod_1"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "runnerFrameL_2__stabilizerRod_2": {"id":"runnerFrameL_2__stabilizerRod_2","a":"runnerFrameL_2","b":"stabilizerRod_2"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "runnerFrameR_2__stabilizerRod_2": {"id":"runnerFrameR_2__stabilizerRod_2","a":"runnerFrameR_2","b":"stabilizerRod_2"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "sidePanelL__topPanel": {"id":"sidePanelL__topPanel","a":"sidePanelL","b":"topPanel","kind":"press"},
  "bottomPanel__sidePanelL": {"id":"bottomPanel__sidePanelL","a":"bottomPanel","b":"sidePanelL","kind":"press"},
  "sidePanelR__topPanel": {"id":"sidePanelR__topPanel","a":"sidePanelR","b":"topPanel","kind":"press"},
  "bottomPanel__sidePanelR": {"id":"bottomPanel__sidePanelR","a":"bottomPanel","b":"sidePanelR","kind":"press"},
  "drawerFront_1__runnerBracketL_1": {"id":"drawerFront_1__runnerBracketL_1","a":"drawerFront_1","b":"runnerBracketL_1"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "drawerFront_1__runnerBracketR_1": {"id":"drawerFront_1__runnerBracketR_1","a":"drawerFront_1","b":"runnerBracketR_1"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "drawerBack_1__drawerSideR_1": {"id":"drawerBack_1__drawerSideR_1","a":"drawerBack_1","b":"drawerSideR_1"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "drawerBack_1__drawerSideL_1": {"id":"drawerBack_1__drawerSideL_1","a":"drawerBack_1","b":"drawerSideL_1"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "drawerBottom_1__drawerSideL_1": {"id":"drawerBottom_1__drawerSideL_1","a":"drawerBottom_1","b":"drawerSideL_1","kind":"slide","mover":"drawerBottom_1"},
  "drawerBottom_1__drawerSideR_1": {"id":"drawerBottom_1__drawerSideR_1","a":"drawerBottom_1","b":"drawerSideR_1","kind":"slide","mover":"drawerBottom_1"},
  "drawerBottom_1__drawerFront_1": {"id":"drawerBottom_1__drawerFront_1","a":"drawerBottom_1","b":"drawerFront_1","kind":"slide","mover":"drawerBottom_1"},
  "drawerFront_1__drawerSideL_1": {"id":"drawerFront_1__drawerSideL_1","a":"drawerFront_1","b":"drawerSideL_1","kind":"press"},
  "drawerFront_1__drawerSideR_1": {"id":"drawerFront_1__drawerSideR_1","a":"drawerFront_1","b":"drawerSideR_1","kind":"press"},
  "drawerFront_2__runnerBracketR_2": {"id":"drawerFront_2__runnerBracketR_2","a":"drawerFront_2","b":"runnerBracketR_2"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "drawerFront_2__runnerBracketL_2": {"id":"drawerFront_2__runnerBracketL_2","a":"drawerFront_2","b":"runnerBracketL_2"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "drawerBack_2__drawerSideR_2": {"id":"drawerBack_2__drawerSideR_2","a":"drawerBack_2","b":"drawerSideR_2"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "drawerBack_2__drawerSideL_2": {"id":"drawerBack_2__drawerSideL_2","a":"drawerBack_2","b":"drawerSideL_2"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "drawerBottom_2__drawerSideL_2": {"id":"drawerBottom_2__drawerSideL_2","a":"drawerBottom_2","b":"drawerSideL_2","kind":"slide","mover":"drawerBottom_2"},
  "drawerBottom_2__drawerSideR_2": {"id":"drawerBottom_2__drawerSideR_2","a":"drawerBottom_2","b":"drawerSideR_2","kind":"slide","mover":"drawerBottom_2"},
  "drawerBottom_2__drawerFront_2": {"id":"drawerBottom_2__drawerFront_2","a":"drawerBottom_2","b":"drawerFront_2","kind":"slide","mover":"drawerBottom_2"},
  "drawerFront_2__drawerSideL_2": {"id":"drawerFront_2__drawerSideL_2","a":"drawerFront_2","b":"drawerSideL_2","kind":"press"},
  "drawerFront_2__drawerSideR_2": {"id":"drawerFront_2__drawerSideR_2","a":"drawerFront_2","b":"drawerSideR_2","kind":"press"},
  "runnerCarriageL_1__runnerMiddleL_1": {"id":"runnerCarriageL_1__runnerMiddleL_1","a":"runnerCarriageL_1","b":"runnerMiddleL_1","kind":"press"},
  "runnerCarriageL_1__runnerClip_1": {"id":"runnerCarriageL_1__runnerClip_1","a":"runnerCarriageL_1","b":"runnerClip_1","kind":"slide","mover":"runnerClip_1"},
  "runnerFrameL_1__runnerMiddleL_1": {"id":"runnerFrameL_1__runnerMiddleL_1","a":"runnerFrameL_1","b":"runnerMiddleL_1","kind":"press"},
  "runnerCarriageL_2__runnerMiddleL_2": {"id":"runnerCarriageL_2__runnerMiddleL_2","a":"runnerCarriageL_2","b":"runnerMiddleL_2","kind":"press"},
  "runnerCarriageR_1__runnerMiddleR_1": {"id":"runnerCarriageR_1__runnerMiddleR_1","a":"runnerCarriageR_1","b":"runnerMiddleR_1","kind":"press"},
  "runnerCarriageR_2__runnerMiddleR_2": {"id":"runnerCarriageR_2__runnerMiddleR_2","a":"runnerCarriageR_2","b":"runnerMiddleR_2","kind":"press"},
  "runnerCarriageL_2__runnerClip_2": {"id":"runnerCarriageL_2__runnerClip_2","a":"runnerCarriageL_2","b":"runnerClip_2","kind":"slide","mover":"runnerClip_2"},
  "runnerCarriageR_1__runnerClip_3": {"id":"runnerCarriageR_1__runnerClip_3","a":"runnerCarriageR_1","b":"runnerClip_3","kind":"slide","mover":"runnerClip_3"},
  "runnerCarriageR_2__runnerClip_4": {"id":"runnerCarriageR_2__runnerClip_4","a":"runnerCarriageR_2","b":"runnerClip_4","kind":"slide","mover":"runnerClip_4"},
  "runnerFrameL_2__runnerMiddleL_2": {"id":"runnerFrameL_2__runnerMiddleL_2","a":"runnerFrameL_2","b":"runnerMiddleL_2","kind":"press"},
  "runnerFrameR_1__runnerMiddleR_1": {"id":"runnerFrameR_1__runnerMiddleR_1","a":"runnerFrameR_1","b":"runnerMiddleR_1","kind":"press"},
  "runnerFrameR_2__runnerMiddleR_2": {"id":"runnerFrameR_2__runnerMiddleR_2","a":"runnerFrameR_2","b":"runnerMiddleR_2","kind":"press"},
} as unknown as LiaisonMap;
