// GENERATED by scripts/gen-thumbs.mjs - do not edit by hand.
// Run: npm run gen:thumbs

import type { ClusterThumbMap, ThumbMap, ThumbSet } from "@/src/game/core/type";

export const thumbnail = { light: require("../../../../assets/thumbnails/furnitures/EKET/light/EKET.png") } satisfies ThumbSet;

export const thumbs = {
  "backPanel": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_backPanel.png") },
  "bolt128918": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/drawerA_bolt128918.png") },
  "bottomPanel": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_bottomPanel.png") },
  "cam139434": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_cam139434.png") },
  "dowel139435": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_dowel139435.png") },
  "dowel145572": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_dowel145572.png") },
  "drawerBack": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/drawerA_drawerBack.png") },
  "drawerBottom": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/drawerA_drawerBottom.png") },
  "drawerFront": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/drawerA_drawerFront.png") },
  "drawerSideL": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/drawerA_drawerSideL.png") },
  "drawerSideR": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/drawerA_drawerSideR.png") },
  "runnerBracketL": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/drawerA_runnerBracketL.png") },
  "runnerBracketR": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/drawerA_runnerBracketR.png") },
  "runnerCarriageL": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_runnerCarriageL.png") },
  "runnerCarriageR": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_runnerCarriageR.png") },
  "runnerClip": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_runnerClip.png") },
  "runnerFrameL": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_runnerFrameL.png") },
  "runnerFrameR": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_runnerFrameR.png") },
  "runnerMiddleL": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_runnerMiddleL.png") },
  "runnerMiddleR": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_runnerMiddleR.png") },
  "screw100349": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_screw100349.png") },
  "screw109041": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/drawerA_screw109041.png") },
  "screw110519": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/drawerA_screw110519.png") },
  "sidePanelL": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_sidePanelL.png") },
  "sidePanelR": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_sidePanelR.png") },
  "stabilizerRod": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_stabilizerRod.png") },
  "suspBracket": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_suspBracket.png") },
  "suspCap": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_suspCap.png") },
  "suspCover": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_suspCover.png") },
  "suspKnob": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_suspKnob.png") },
  "topPanel": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/parts/cabinet_topPanel.png") },
} as ThumbMap;

export const clusterThumbs = {
  "cabinet": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/clusters/cabinet.png") },
  "drawerA": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/clusters/drawerA.png") },
  "drawerB": { light: require("../../../../assets/thumbnails/furnitures/EKET/light/clusters/drawerB.png") },
} as ClusterThumbMap;
