// GENERATED by src/game/helper-scripts/derive-boxes.mts — do not edit. Re-run after any LACK.glb re-export.
import type { PartBox, PartId } from "@/src/game/core/type";

export const BOXES: Record<PartId, PartBox> = {
  "bolt115980_1": { min: [0.243173, 0.3655, -0.253827], max: [0.253827, 0.4355, -0.243173] },
  "bolt115980_2": { min: [0.243628, 0.3655, 0.243627], max: [0.253372, 0.4355, 0.253373] },
  "bolt115980_3": { min: [-0.253218, 0.3655, 0.243781], max: [-0.243782, 0.4355, 0.253219] },
  "bolt115980_4": { min: [-0.252639, 0.3655, -0.252639], max: [-0.244361, 0.4355, -0.244361] },
  "leg_1": { min: [0.224, 0, -0.273], max: [0.273, 0.4, -0.224] },
  "leg_2": { min: [0.224, 0, 0.224], max: [0.273, 0.4, 0.273] },
  "leg_3": { min: [-0.273, 0, 0.224], max: [-0.224, 0.4, 0.273] },
  "leg_4": { min: [-0.273, 0, -0.273], max: [-0.224, 0.4, -0.224] },
  "tableTop": { min: [-0.275, 0.4, -0.275], max: [0.275, 0.449, 0.275] },
} as Record<PartId, PartBox>;
