// GENERATED by src/game/helper-scripts/derive-joints.mts — do not edit by hand.
// Travel axes derived from the contact slabs at baked pose (core/derive/jointGeometry.ts). Regenerate after any model re-export or JOINTS/STRUCTURE change; the derivedJoints pin test fails, named, when this file is stale.
// 5 derived, 0 undetermined:
//   (none)
import type { JointGeometry } from "@/src/game/core/type";

export const JOINT_GEOMETRY = {
  "leg_1": {"placeDir":[0,1,0]},   // snap ↔ tableTop, hardware, sign: toward-partner
  "leg_2": {"placeDir":[0,1,0]},   // snap ↔ tableTop, hardware, sign: toward-partner
  "leg_3": {"placeDir":[0,1,0]},   // snap ↔ tableTop, hardware, sign: toward-partner
  "leg_4": {"placeDir":[0,1,0]},   // snap ↔ tableTop, hardware, sign: toward-partner
  "tableTop": {"placeDir":[0,-1,0]},   // snap ↔ leg_4, hardware, sign: toward-partner
} as JointGeometry;
