// GENERATED by src/game/helper-scripts/derive-structure.mts — do not edit by hand.
// Γ: the liaison graph core/model/liaisons.ts derives from the COMPOSED parts (structure.gen.ts spread over parts.gen.ts) — every joint the game knows about, with the mover and kind each one carries. The frontier, the build order, the joint frames and every blockReason read this.
// Nothing here is authored. An edge exists because a part names a join target or because a fastener names both endpoints, and its kind is either lowered from a JOINT or NAMED by the snap heuristic; the per-line notes say which.
// Regenerate after any JOINTS/FASTENERS/STRUCTURE change or model re-export; the liaisons pin test fails, named, when this file is stale.
// 4 edges: 4 snap
import type { LiaisonMap } from "@/src/game/core/type";

export const LIAISONS = {
  "leg_4__tableTop": {"id":"leg_4__tableTop","a":"leg_4","b":"tableTop","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "leg_2__tableTop": {"id":"leg_2__tableTop","a":"leg_2","b":"tableTop","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "leg_1__tableTop": {"id":"leg_1__tableTop","a":"leg_1","b":"tableTop","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "leg_3__tableTop": {"id":"leg_3__tableTop","a":"leg_3","b":"tableTop","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
} as unknown as LiaisonMap;
