// GENERATED by src/game/helper-scripts/derive-joints.mts — do not edit by hand.
// This furniture authors no JOINTS, so its composed structure IS its authored STRUCTURE. Re-exported so every consumer imports the same name whether or not a furniture has migrated; the day it authors one, this file becomes a literal.
export { STRUCTURE as STRUCTURE_COMPOSED } from "./authored";
