// GENERATED by src/game/helper-scripts/derive-sweep.mts — do not edit by hand.
// Exit-sweep blockers per structural part per cardinal direction (see core/model/sweep.ts). Regenerate after any model re-export or STRUCTURE re-typing; the structuralSweep pin test fails, named, when this file is stale.
import type { SweepMap } from "@/src/game/core/type";

export const SWEEP = {
  "leg_1": {"+y":["tableTop"]},
  "leg_2": {"+y":["tableTop"]},
  "leg_3": {"+y":["tableTop"]},
  "leg_4": {"+y":["tableTop"]},
  "tableTop": {"-y":["leg_1","leg_2","leg_3","leg_4"]},
} as SweepMap;
