// GENERATED by scripts/gen-thumbs.mjs - do not edit by hand.
// Run: npm run gen:thumbs

import type { ThumbMap, ThumbSet } from "@/src/game/core/type";

export const thumbnail = { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/BEKVAM.png") } satisfies ThumbSet;

export const thumbs = {
  "backBottomRail": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_backBottomRail.png") },
  "backTopRail": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_backTopRail.png") },
  "dowel101350": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_dowel101350.png") },
  "frontBottomRail": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_frontBottomRail.png") },
  "frontTopRail": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_frontTopRail.png") },
  "legL": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_legL.png") },
  "legR": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_legR.png") },
  "screw105111": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_screw105111.png") },
  "screw105215": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_screw105215.png") },
  "step": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_step.png") },
  "topPlane": { light: require("../../../../assets/thumbnails/furnitures/BEKVAM/light/parts/whole_topPlane.png") },
} as ThumbMap;
