// GENERATED by scripts/generate-eket-prototype-assets.mjs — do not edit by hand.
// engage direction: world-space unit vector from a connector's seated pose toward the tool side.
import type { PartId } from './parts';

export const ENGAGE_DIR: Partial<Record<PartId, readonly [number, number, number]>> = {
  connector_1: [0, 1, 0],
};
