// GENERATED by scripts/generate-eket-prototype-assets.mjs — do not edit by hand.
// Simplified EKET cabinet prototype poses, world space, meters.
export interface PartPose {
  position: [number, number, number];
  rotation: [number, number, number, number]; // quaternion xyzw
}

export const PART_POSES = {
  bottom_panel: { position: [0, 0.01, 0], rotation: [0, 0, 0, 1] },
  left_side_panel: { position: [-0.17, 0.18, 0], rotation: [0, 0, 0, 1] },
  right_side_panel: { position: [0.17, 0.18, 0], rotation: [0, 0, 0, 1] },
  back_panel: { position: [0, 0.18, -0.12], rotation: [0, 0, 0, 1] },
  top_panel: { position: [0, 0.35, 0], rotation: [0, 0, 0, 1] },
  connector_1: { position: [0.14, 0.335, -0.095], rotation: [0, 0, 0, 1] },
} as const satisfies Record<string, PartPose>;

export type PosedPartId = keyof typeof PART_POSES;
