// GENERATED by src/game/helper-scripts/derive-structure.mts — do not edit by hand.
// Travel axes derived from the contact slabs at baked pose (core/derive/jointGeometry.ts). Regenerate after any model re-export or JOINTS/STRUCTURE change; the derivedJoints pin test fails, named, when this file is stale.
// 6 derived, 2 undetermined:
//   backTopRail: both signs have third-party blockers in the exit corridor
//   frontTopRail: both signs have third-party blockers in the exit corridor
import type { JointGeometry } from "@/src/game/core/type";

export const JOINT_GEOMETRY = {
  "backBottomRail": {"placeDir":[-1,0,0]},   // snap ↔ legR, normal, ext [0.04,0.06,0.05], sign: toward-partner
  "frontBottomRail": {"placeDir":[1,0,0]},   // snap ↔ legR, normal, ext [0.04,0.06,0.05], sign: toward-partner
  "legL": {"placeDir":[0,0,1]},   // snap ↔ backTopRail, normal, ext [0.04,0.06,0.02], sign: toward-partner
  "legR": {"placeDir":[0,0,-1]},   // snap ↔ step, hardware, sign: toward-partner
  "step": {"placeDir":[0,0,-1]},   // snap ↔ legL, hardware, sign: toward-partner
  "topPlane": {"placeDir":[0,-1,0]},   // snap ↔ backTopRail, normal, ext [0.04,0.02,0.33], sign: toward-partner
} as JointGeometry;
