// GENERATED by src/game/helper-scripts/derive-joints.mts — do not edit by hand.
// Travel axes derived from the contact slabs at baked pose (core/model/jointGeometry.ts). Regenerate after any model re-export or JOINTS/STRUCTURE change; the derivedJoints pin test fails, named, when this file is stale.
// 4 derived, 4 undetermined:
//   backTopRail: several unblocked contacts claim different travel — order-dependent, resolved at runtime, not here
//   frontBottomRail: several unblocked contacts claim different travel — order-dependent, resolved at runtime, not here
//   frontTopRail: several unblocked contacts claim different travel — order-dependent, resolved at runtime, not here
//   legL: several unblocked contacts claim different travel — order-dependent, resolved at runtime, not here
import type { JointGeometry } from "@/src/game/core/type";

export const JOINT_GEOMETRY = {
  "backBottomRail": {"placeDir":[-1,0,0]},   // snap ↔ legR, normal, ext [0.04,0.06,0.05], sign: toward-partner
  "legR": {"placeDir":[0,-1,0]},   // snap ↔ step, normal, ext [0.15,0.04,0.07], sign: toward-partner
  "step": {"placeDir":[0,1,0]},   // snap ↔ legL, normal, ext [0.15,0.04,0.07], sign: toward-partner
  "topPlane": {"placeDir":[0,-1,0]},   // snap ↔ backTopRail, normal, ext [0.04,0.02,0.33], sign: toward-partner
} as JointGeometry;
