// GENERATED by src/game/helper-scripts/derive-structure.mts — do not edit by hand.
// Γ: the liaison graph core/model/liaisons.ts derives from the COMPOSED parts (structure.gen.ts spread over parts.gen.ts) — every joint the game knows about, with the mover and kind each one carries. The frontier, the build order, the joint frames and every blockReason read this.
// Nothing here is authored. An edge exists because a part names a join target or because a fastener names both endpoints, and its kind is either lowered from a JOINT or NAMED by the snap heuristic; the per-line notes say which.
// Regenerate after any JOINTS/FASTENERS/STRUCTURE change or model re-export; the liaisons pin test fails, named, when this file is stale.
// 13 edges: 11 (unnamed), 2 snap
import type { LiaisonMap } from "@/src/game/core/type";

export const LIAISONS = {
  "backTopRail__topPlane": {"id":"backTopRail__topPlane","a":"backTopRail","b":"topPlane"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "frontTopRail__topPlane": {"id":"frontTopRail__topPlane","a":"frontTopRail","b":"topPlane"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "frontBottomRail__step": {"id":"frontBottomRail__step","a":"frontBottomRail","b":"step"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "frontBottomRail__legR": {"id":"frontBottomRail__legR","a":"frontBottomRail","b":"legR"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "backTopRail__legR": {"id":"backTopRail__legR","a":"backTopRail","b":"legR"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "frontTopRail__legR": {"id":"frontTopRail__legR","a":"frontTopRail","b":"legR"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "backBottomRail__legR": {"id":"backBottomRail__legR","a":"backBottomRail","b":"legR"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "frontBottomRail__legL": {"id":"frontBottomRail__legL","a":"frontBottomRail","b":"legL"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "backTopRail__legL": {"id":"backTopRail__legL","a":"backTopRail","b":"legL"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "frontTopRail__legL": {"id":"frontTopRail__legL","a":"frontTopRail","b":"legL"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "backBottomRail__legL": {"id":"backBottomRail__legL","a":"backBottomRail","b":"legL"},   // UNNAMED — hardware-made, but an endpoint states a travel
  "legR__step": {"id":"legR__step","a":"legR","b":"step","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
  "legL__step": {"id":"legL__step","a":"legL","b":"step","kind":"snap"},   // NAMED by the heuristic — hardware-made, neither endpoint states a travel
} as unknown as LiaisonMap;
