// GENERATED by src/game/helper-scripts/derive-joints.mts — do not edit by hand.
// The authored STRUCTURE with this furniture's JOINTS lowered into it — what applyStructure spreads over the mesh facts, and therefore what the game actually runs. Review THIS to see a joint's consequences: the join array a joint emitted (or deliberately did not, where hardware already makes the edge), the dropOn it did or did not add, and the travel it took from joints.gen.
// Regenerate after any JOINTS/STRUCTURE change or model re-export; the derivedJoints pin test fails, named, when this file is stale.
import type { StructureOverlay } from "@/src/game/core/model/liaisons";

export const STRUCTURE_COMPOSED = {
  "backBottomRail": {"placeDir":[-1,0,0],"unstable":true},
  "backTopRail": {"placeDir":[-1,0,0],"unstable":true},
  "dowel101350_1": {"noVisibilityGate":true},
  "dowel101350_2": {"noVisibilityGate":true},
  "frontBottomRail": {"placeDir":[1,0,0],"unstable":true},
  "frontTopRail": {"placeDir":[1,0,0],"unstable":true},
  "legL": {"seed":true},
  "legR": {"seed":true},
  "screw105111_1": {"noVisibilityGate":true},
  "screw105111_2": {"noVisibilityGate":true},
  "screw105111_3": {"noVisibilityGate":true},
  "step": {"seed":true},
  "topPlane": {"placeDir":[0,-1,0]},
} as unknown as StructureOverlay;
