// GENERATED by src/game/helper-scripts/derive-structure.mts — do not edit by hand.
// The authored STRUCTURE with this furniture's JOINTS lowered into it and its FASTENERS' role facts on every instance — what applyStructure spreads over the mesh facts, and therefore what the game actually runs. Review THIS to see a joint's or a def's consequences: the join array a joint emitted (or deliberately did not, where hardware already makes the edge), the dropOn it did or did not add, the travel it took from joints.gen, the role and preload each fastener carries.
// Regenerate after any JOINTS/FASTENERS/STRUCTURE change or model re-export; the derivedJoints pin test fails, named, when this file is stale.
import type { StructureOverlay } from "@/src/game/core/model/liaisons";

export const STRUCTURE_COMPOSED = {
  "backBottomRail": {"placeDir":[-1,0,0],"unstable":true},
  "backTopRail": {"placeDir":[-1,0,0],"unstable":true},
  "dowel101350_1": {"fastenerRole":"connector","preload":{"completesOn":"insert","counterpartMountsBy":"press"},"noVisibilityGate":true},
  "dowel101350_2": {"fastenerRole":"connector","preload":{"completesOn":"insert","counterpartMountsBy":"press"},"noVisibilityGate":true},
  "frontBottomRail": {"placeDir":[1,0,0],"unstable":true},
  "frontTopRail": {"placeDir":[1,0,0],"unstable":true},
  "legL": {"seed":true},
  "legR": {"seed":true},
  "screw105111_1": {"fastenerRole":"securer","noVisibilityGate":true},
  "screw105111_2": {"fastenerRole":"securer","noVisibilityGate":true},
  "screw105111_3": {"fastenerRole":"securer","noVisibilityGate":true},
  "screw105215_1": {"fastenerRole":"securer"},
  "screw105215_2": {"fastenerRole":"securer"},
  "screw105215_3": {"fastenerRole":"securer"},
  "screw105215_4": {"fastenerRole":"securer"},
  "screw105215_5": {"fastenerRole":"securer"},
  "screw105215_6": {"fastenerRole":"securer"},
  "screw105215_7": {"fastenerRole":"securer"},
  "screw105215_8": {"fastenerRole":"securer"},
  "step": {"seed":true},
  "topPlane": {"placeDir":[0,-1,0]},
} as unknown as StructureOverlay;
