// GENERATED by src/game/helper-scripts/derive-sweep.mts — do not edit by hand.
// Exit-sweep blockers per structural part per cardinal direction (see core/model/sweep.ts). Regenerate after any model re-export or STRUCTURE re-typing; the structuralSweep pin test fails, named, when this file is stale.
import type { SweepMap } from "@/src/game/core/type";

export const SWEEP = {
  "backBottomRail": {"+y":["legL","legR"],"+z":["legR"],"-z":["legL"]},
  "backTopRail": {"+y":["legL","topPlane"],"-y":["legL"],"+z":["legR"],"-z":["legL"]},
  "frontBottomRail": {"+y":["step"],"+z":["legR"],"-z":["legL"]},
  "frontTopRail": {"+y":["legL","topPlane"],"-y":["legL"],"+z":["legR"],"-z":["legL"]},
  "legL": {"+x":["step"],"-x":["step"],"+y":["backBottomRail","backTopRail","frontTopRail","step","topPlane"],"-y":["backBottomRail","backTopRail","frontTopRail","step"],"+z":["backBottomRail","backTopRail","frontBottomRail","frontTopRail","step"]},
  "legR": {"+x":["step"],"-x":["step"],"+y":["backBottomRail","step","topPlane"],"-y":["backBottomRail","backTopRail","frontTopRail","step"],"-z":["backBottomRail","backTopRail","frontBottomRail","frontTopRail","step"]},
  "step": {"+x":["legL","legR"],"-x":["legL"],"+y":["legL","legR"],"-y":["frontBottomRail","legL","legR"],"+z":["legR"],"-z":["legL"]},
  "topPlane": {"-y":["backTopRail","frontTopRail","legL","legR"]},
} as SweepMap;
