// Regenerates each furniture's sweep.gen.ts — the exit-sweep blocker data (core/model/sweep.ts) derived from the GLB's final poses. Run after any model re-export or STRUCTURE re-typing:
//   npx tsx src/game/helper-scripts/derive-sweep.mts
// Structural parts only, swept per cluster; parkBackoff (via applyStructure) bounds each part's travel span. Output is deterministic (sorted parts, sorted blocker lists), so a diff after regeneration is a real geometry/authoring change. The structuralSweep.furniture.test.ts pin asserts the checked-in files match a fresh computation — a stale file fails there, named.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { partsForSweep, sweepFurniture, type AuthoredModule } from "@/src/game/core/derive/pipeline";
import { readGlbMeshes, type GlbMesh } from "@/src/game/core/derive/glb";
import type { PartDef, PartId } from "@/src/game/core/type";

import * as LACK from "@/src/game/content/furnitures/LACK/authored";
import { PARTS as LACK_PARTS } from "@/src/game/content/furnitures/LACK/parts.gen";
import * as BEKVAM from "@/src/game/content/furnitures/BEKVAM/authored";
import { PARTS as BEKVAM_PARTS } from "@/src/game/content/furnitures/BEKVAM/parts.gen";
import * as DALFRED from "@/src/game/content/furnitures/DALFRED/authored";
import { PARTS as DALFRED_PARTS } from "@/src/game/content/furnitures/DALFRED/parts.gen";
import * as EKET from "@/src/game/content/furnitures/EKET/authored";
import { PARTS as EKET_PARTS } from "@/src/game/content/furnitures/EKET/parts.gen";

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const MODELS = path.join(ROOT, "..", "..", "assets", "models", "furnitures");
const OUT = path.join(ROOT, "..", "content", "furnitures");

const worldTris = (file: string): Map<string, GlbMesh["tris"]> =>
  new Map(readGlbMeshes(fs.readFileSync(file)).map((m) => [m.partId, m.tris]));

// JOINTS ride along because a joint's `approach.back` IS the part's parkBackoff, and the backoff bounds the travel span this file sweeps — see `partsForSweep`, which is also what structuralSweep.furniture.test.ts recomputes against, so the pin and the generator cannot compose the parts differently.
const CORPUS: [string, Record<PartId, PartDef>, AuthoredModule][] = [
  ["LACK", LACK_PARTS, LACK as AuthoredModule],
  ["BEKVAM", BEKVAM_PARTS, BEKVAM as AuthoredModule],
  ["DALFRED", DALFRED_PARTS, DALFRED as AuthoredModule],
  ["EKET", EKET_PARTS, EKET as AuthoredModule],
];

for (const [id, raw, mod] of CORPUS) {
  const parts = partsForSweep(raw, mod);
  const tris = worldTris(path.join(MODELS, id, `${id}.glb`));
  const sweep = sweepFurniture(parts, tris);
  const body = Object.keys(sweep).sort().map((pid) => `  ${JSON.stringify(pid)}: ${JSON.stringify(sweep[pid as PartId])},`).join("\n");
  const out = path.join(OUT, id, "sweep.gen.ts");
  fs.writeFileSync(
    out,
    `// GENERATED by src/game/helper-scripts/derive-sweep.mts — do not edit by hand.
// Exit-sweep blockers per structural part per cardinal direction (see core/model/sweep.ts). Regenerate after any model re-export or STRUCTURE re-typing; the structuralSweep pin test fails, named, when this file is stale.
import type { SweepMap } from "@/src/game/core/type";

export const SWEEP = {
${body}
} as SweepMap;
`,
  );
  console.log(`${id}: wrote ${Object.keys(sweep).length} swept parts → ${out}`);
}
