// Regenerates each furniture's boxes.gen.ts — per-part world bounds at baked pose, read from the GLB. Run after any model re-export:
//   npx tsx src/game/helper-scripts/derive-boxes.mts
// Refuses to write a furniture whose mesh bounds disagree with parts.gen by more than TOLERANCE_MM: that gap means a re-export moved
// something, and a wrong box is worse than none (the drag trusts it completely). The boxes.furniture.test.ts pin fails on a stale file.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { deriveBoxes, TOLERANCE_MM } from "@/src/game/core/derive/boxes";
import type { PartDef, PartId } from "@/src/game/core/type";

import { PARTS as LACK_PARTS } from "@/src/game/content/furnitures/LACK/parts.gen";
import { PARTS as BEKVAM_PARTS } from "@/src/game/content/furnitures/BEKVAM/parts.gen";
import { PARTS as DALFRED_PARTS } from "@/src/game/content/furnitures/DALFRED/parts.gen";
import { PARTS as EKET_PARTS } from "@/src/game/content/furnitures/EKET/parts.gen";

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const MODELS = path.join(ROOT, "..", "..", "assets", "models", "furnitures");
const OUT = path.join(ROOT, "..", "content", "furnitures");

const CORPUS: [string, Record<PartId, PartDef>][] = [
  ["LACK", LACK_PARTS],
  ["BEKVAM", BEKVAM_PARTS],
  ["DALFRED", DALFRED_PARTS],
  ["EKET", EKET_PARTS],
];

const v3 = (v: readonly number[]): string => `[${v.join(", ")}]`;

let failed = 0;
for (const [id, parts] of CORPUS) {
  const bytes = new Uint8Array(fs.readFileSync(path.join(MODELS, id, `${id}.glb`)));
  const { boxes, drift } = deriveBoxes(bytes, parts);

  if (drift.length) {
    failed++;
    const worst = drift.slice().sort((a, b) => b.mm - a.mm);
    console.error(`${id}: NOT WRITTEN — ${drift.length} part(s) more than ${TOLERANCE_MM}mm from pose+visualCenterOffset:`);
    for (const d of worst.slice(0, 8)) console.error(`  ${d.partId}  ${d.mm.toFixed(1)}mm`);
    continue;
  }

  const missing = Object.keys(parts).filter((p) => !boxes[p as PartId]);
  const body = Object.entries(boxes)
    .map(([partId, b]) => `  "${partId}": { min: ${v3(b.min)}, max: ${v3(b.max)} },`)
    .join("\n");
  const file = `// GENERATED by src/game/helper-scripts/derive-boxes.mts — do not edit. Re-run after any ${id}.glb re-export.
import type { PartBox, PartId } from "@/src/game/core/type";

export const BOXES: Record<PartId, PartBox> = {
${body}
} as Record<PartId, PartBox>;
`;
  fs.writeFileSync(path.join(OUT, id, "boxes.gen.ts"), file);
  console.log(`${id}: ${Object.keys(boxes).length} boxes${missing.length ? ` (${missing.length} part(s) with no mesh node: ${missing.join(", ")})` : ""}`);
}

if (failed) process.exit(1);
