// Generates audio.gen.ts for each furniture from recorded/TTS step clips.
//
// Layout (matches src/assets/audio/furnitures/):
//   instructions/<ID>/<actionId>.<ext>   one spoken clip per assembly step  → Furniture.audio parts/<ID>/<group>.<ext>             one clip per part GROUP name        → (reserved; LabelSet.audio) where <ID> is the furniture id, <actionId> a step id (place_circleUpp, insert_screw105251_1, tighten_pole, …), <group> a part group (leg, pole, …), and <ext> ∈ m4a | mp3 | caf | wav.
//
// This script maps the `instructions/<ID>/` clips to a require() keyed by
// ActionId and writes src/game/content/furnitures/<ID>/audio.gen.ts. To wire it in, add to that furniture's index.ts:
//   import { audio } from "./audio.gen";   // …and `audio,` in the Furniture object.
// Furnitures with no clips get no file (audio stays undefined — the UI falls back to reading instructionText). The `parts/` clips aren't wired yet (per-step mode).
//
//   node src/game/helper-scripts/gen-audio.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.resolve(SCRIPT_DIR, "..", "..");
const FURNITURES = path.join(SCRIPT_DIR, "..", "content", "furnitures");
const INSTR_ROOT = path.join(SRC, "assets", "audio", "furnitures", "instructions");
// require() path is relative to data/furnitures/<ID>/audio.gen.ts
const REQUIRE_PREFIX = "../../../../assets/audio/furnitures/instructions";

const EXTS = new Set([".m4a", ".mp3", ".caf", ".wav"]);

function clipsFor(id) {
  const dir = path.join(INSTR_ROOT, id);
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => EXTS.has(path.extname(f).toLowerCase()))
    .sort();
}

function emit(id, files) {
  const rows = files
    .map((f) => {
      const actionId = path.basename(f, path.extname(f));
      return `  ${JSON.stringify(actionId)}: require("${REQUIRE_PREFIX}/${id}/${f}"),`;
    })
    .join("\n");

  const out = path.join(FURNITURES, id, "audio.gen.ts");
  fs.writeFileSync(
    out,
    `// GENERATED by scripts/gen-audio.mjs - do not edit by hand.
// Run: npm run gen:audio
import type { AudioMap } from "@/src/game/core/type";

export const audio = {
${rows}
} as AudioMap;
`,
  );
  console.log(
    `${id}: wrote ${files.length} clip(s) → ${path.relative(SRC, out)} ` +
      `(remember to wire \`audio\` into ${id}/index.ts)`,
  );
}

if (!fs.existsSync(INSTR_ROOT)) {
  console.log(`no audio at ${path.relative(SRC, INSTR_ROOT)} — nothing to do`);
} else {
  const ids = fs
    .readdirSync(INSTR_ROOT)
    .filter((id) => fs.statSync(path.join(INSTR_ROOT, id)).isDirectory());
  if (ids.length === 0) console.log("no furniture folders under instructions/ — nothing to do");
  for (const id of ids) {
    const files = clipsFor(id);
    if (files.length === 0) {
      console.log(`${id}: no instruction clips — skipped`);
      continue;
    }
    emit(id, files);
  }
}
