export function emitAuthored(draft, extras) {
  const L = [];
  L.push(`// GENERATED by tools/processGLB — starting point; refine against the manual`);
  L.push(`// (seeds, slide/screw intent, stages, requires, beats), then iterate with:`);
  L.push(`//   npm run furniture:validate ${draft.id} && npm run furniture:test ${draft.id}`);
  L.push(`import { action, FastenerRule } from "@/src/game/core/composition/composeActions";`);
  L.push(`import { StructureOverlay } from "@/src/game/core/model/liaisons";`);
  L.push(`import { asGroupId } from "@/src/game/core/ids";`);
  L.push(`import { ClusterDef, ClusterId, DraftAction, InstructionSet, LabelMap } from "@/src/game/core/type";`);
  L.push(``);
  L.push(`export const META = {`);
  L.push(`  name: ${JSON.stringify(draft.meta.name)},`);
  L.push(`  brand: ${JSON.stringify(extras.brand ?? "IKEA")},`);
  L.push(`  category: ${JSON.stringify(extras.category ?? "Other")},`);
  L.push(`  difficulty: ${draft.meta.difficulty},`);
  L.push(`  duration: ${draft.meta.duration},`);
  L.push(`  link: ${JSON.stringify(extras.link ?? "")},`);
  L.push(`} as const;`);
  L.push(``);
  L.push(`export const LABELS = {`);
  for (const [g, label] of Object.entries(draft.labels))
    L.push(`  ${g}: { standard: ${JSON.stringify(label)} },`);
  L.push(`} as LabelMap;`);
  L.push(``);
  L.push(`export const CLUSTERS = {`);
  for (const c of draft.clusters)
    L.push(`  ${c.id}: { id: ${JSON.stringify(c.id)}, label: ${JSON.stringify(c.label)} },`);
  L.push(`} as Record<ClusterId, ClusterDef>;`);
  L.push(``);
  L.push(`export const STRUCTURE: StructureOverlay = {`);
  const seeds = new Set(draft.placements.filter((p) => p.stage === 1 && p.requires.length === 0)
    .reduce((acc, p) => { if (!acc.some((q) => q.cluster === p.cluster)) acc.push(p); return acc; }, [])
    .map((p) => p.partId));
  const joinsByLater = new Map();
  for (const j of draft.joints.filter((j) => !j.crossCluster))
    (joinsByLater.get(j.later) ?? joinsByLater.set(j.later, []).get(j.later))
      .push(j.later === j.a ? j.b : j.a);
  for (const p of draft.placements) {
    const fields = [];
    if (seeds.has(p.partId)) fields.push("seed: true");
    const dj = joinsByLater.get(p.partId);
    if (dj?.length) fields.push(`directJoins: [${dj.map((x) => JSON.stringify(x)).join(", ")}]`);
    L.push(`  ${p.partId}: { ${fields.join(", ")}${fields.length ? " " : ""}},`);
  }
  L.push(`} as StructureOverlay;`);
  L.push(``);
  L.push(`export const FASTENER_RULES: FastenerRule[] = [`);
  for (const r of draft.rules)
    L.push(`  { group: asGroupId(${JSON.stringify(r.group)}), stage: ${r.stage} },`);
  L.push(`];`);
  L.push(``);
  L.push(`export const AUTHORED_ACTIONS: DraftAction[] = [`);
  for (const p of draft.placements)
    L.push(`  action({ type: "placePart", stage: ${p.stage}, partId: ${JSON.stringify(p.partId)}, requires: ${JSON.stringify(p.requires)} }),`);
  const multi = draft.clusters.length > 1;
  if (multi)
    for (const c of draft.clusters.slice(1))
      L.push(`  action({ actionId: "combine_${c.id}", type: "combineClusters", stage: ${draft.maxStage + 1}, cluster: ${JSON.stringify(c.id)}, requires: [] }),`);
  L.push(`  action({ actionId: "finishing_checks", type: "reorient", stage: ${draft.maxStage + 1}, requires: [${multi ? draft.clusters.slice(1).map((c) => JSON.stringify("combine_" + c.id)).join(", ") : ""}] }),`);
  L.push(`];`);
  L.push(``);
  L.push(`export const BEATS = {} as InstructionSet;`);
  return L.join("\n") + "\n";
}

const PLACEHOLDER_PNG_B64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";
export const placeholderPng = () => Buffer.from(PLACEHOLDER_PNG_B64, "base64");

export const emitThumbsTs = (id) => `// GENERATED placeholder — regenerate once thumbnail rendering is restored.
import type { ThumbMap, ThumbSet } from "@/src/game/core/type";
const F = require("../../../../assets/thumbnails/furnitures/${id}/light/${id}.png");
export const thumbnail = { light: F, dark: F } satisfies ThumbSet;
export const thumbs = {} as ThumbMap;
`;

export const emitMetaTs = (id) => `import { expandFastenerRules, withOrder } from "@/src/game/core/composition/composeActions";
import { applyStructure } from "@/src/game/core/model/liaisons";
import { metaCounts } from "@/src/game/core/composition/metaCounts";
import { FurnitureMeta } from "@/src/game/core/type";
import { AUTHORED_ACTIONS, FASTENER_RULES, META, STRUCTURE } from "./authored";
import { HARDWARE } from "@/src/game/data/hardware";
import { ALL_PART_IDS, PARTS } from "./parts.gen";
import { thumbnail } from "./thumbs.gen";

const P = applyStructure(PARTS, STRUCTURE);
export const ACTIONS = withOrder(
  [...AUTHORED_ACTIONS, ...expandFastenerRules(FASTENER_RULES, P, HARDWARE)],
  P,
);

export const ${id}_META: FurnitureMeta = {
  id: "${id}",
  name: META.name,
  thumbnail,
  brand: META.brand,
  category: META.category,
  difficulty: META.difficulty,
  duration: META.duration,
  link: META.link,
  ...metaCounts(ALL_PART_IDS, ACTIONS),
};
`;

export const emitIndexTs = (id) => `import { applyStructure, buildLiaisons } from "@/src/game/core/model/liaisons";
import { buildInstructions } from "@/src/game/core/presentation/instructions";
import { Furniture, PartDef } from "@/src/game/core/type";
import { assertValidFurniture } from "@/src/game/core/composition/validateFurniture";
import { composeLabels } from "@/src/game/core/composition/composeLabels";
import { HARDWARE } from "@/src/game/data/hardware";
import { toolsUsed } from "@/src/game/data/tools";
import { BEATS, CLUSTERS, LABELS, STRUCTURE } from "./authored";
import { ACTIONS, ${id}_META } from "./meta";
import { PARTS } from "./parts.gen";
import { thumbs } from "./thumbs.gen";

const P = PARTS as Record<string, PartDef>;
const PARTS_WITH_STRUCTURE = applyStructure(PARTS, STRUCTURE);
const LIAISONS = buildLiaisons(PARTS_WITH_STRUCTURE);
const LABELS_ALL = composeLabels(LABELS, PARTS_WITH_STRUCTURE, HARDWARE);
const INSTRUCTIONS = buildInstructions(ACTIONS, P, LABELS_ALL, BEATS, CLUSTERS);
const model = require("../../../../assets/models/furnitures/${id}/${id}.glb");

export const ${id}: Furniture = {
  meta: ${id}_META,
  model,
  parts: PARTS_WITH_STRUCTURE,
  actions: ACTIONS,
  liaisons: LIAISONS,
  clusters: CLUSTERS,
  thumbs,
  tools: toolsUsed(ACTIONS),
  instructions: INSTRUCTIONS,
  labels: LABELS_ALL,
  xpPerStep: 10,
  xpBonusOnComplete: 100,
};

if (typeof __DEV__ === "undefined" || __DEV__) assertValidFurniture(${id});
`;

export function patchFurnitureId(src, id) {
  if (new RegExp(`"${id}"`).test(src)) throw new Error(`FurnitureId already contains "${id}"`);
  const re = /(export type FurnitureId =\s*(?:"[^"]+"\s*\|\s*)*"[^"]+")(;)/;
  if (!re.test(src)) throw new Error("FurnitureId anchor not found in type.ts");
  return src.replace(re, `$1 | "${id}"$2`);
}

export function patchFurnituresTs(src, id) {
  if (src.includes(`${id}_META`)) throw new Error(`furnitures.ts already registers ${id}`);
  let out = src.replace(/(import { \w+_META } from "\.\/\w+\/meta";)(?![\s\S]*import { \w+_META })/,
    `$1\nimport { ${id}_META } from "./${id}/meta";`);
  out = out.replace(/(FURNITURE_METAS: FurnitureMeta\[\] = \[[^\]]*)\]/, `$1, ${id}_META]`);
  out = out.replace(/(FURNITURE_LOADERS[^{]*\{[\s\S]*?)(\n\};)/,
    `$1\n  ${id}: () => import("./${id}").then((m) => m.${id}),$2`);
  if (!out.includes(`"./${id}"`)) throw new Error("furnitures.ts loader anchor not found");
  return out;
}
