// GENERATED by scripts/gen-thumbs.mjs - do not edit by hand.
// Run: npm run gen:thumbs

import type { ClusterThumbMap, ThumbMap, ThumbSet } from "@/src/game/core/type";

export const thumbnail = { light: require("../../../../assets/thumbnails/furnitures/TUTORIAL/light/TUTORIAL.png") } satisfies ThumbSet;

export const thumbs = {
  "connector": { light: require("../../../../assets/thumbnails/furnitures/TUTORIAL/light/parts/connector_1.png") },
  "panel": { light: require("../../../../assets/thumbnails/furnitures/TUTORIAL/light/parts/bottom_panel.png") },
} as ThumbMap;

export const clusterThumbs = {
  "back": { light: require("../../../../assets/thumbnails/furnitures/TUTORIAL/light/clusters/back.png") },
  "bottom": { light: require("../../../../assets/thumbnails/furnitures/TUTORIAL/light/clusters/bottom.png") },
  "connector": { light: require("../../../../assets/thumbnails/furnitures/TUTORIAL/light/clusters/connector.png") },
  "left": { light: require("../../../../assets/thumbnails/furnitures/TUTORIAL/light/clusters/left.png") },
  "right": { light: require("../../../../assets/thumbnails/furnitures/TUTORIAL/light/clusters/right.png") },
  "top": { light: require("../../../../assets/thumbnails/furnitures/TUTORIAL/light/clusters/top.png") },
} as ClusterThumbMap;
