// A scratch panel for the editing grid's on-device legibility. TEMPORARY — this whole file is meant to be deleted once the numbers below are settled and folded into their real homes.
//
// WHY IT EXISTS. The grid is real geometry: 6 mm world-space quads generated into the shell GLB, five plates, one floor and one per wall. 6 mm projects to about ONE PIXEL at the room's normal framing and to well under one on the far half of the floor and on any wall seen at a grazing angle, and nothing about that can be judged from a screenshot or a test — it has to be looked at, on a phone, at the size it actually ships. Every knob here changes something whose only verdict is the eye, so they are gathered in one file instead of scattered across the three places that consume them.
//
// WHAT THE DEVICE HAS ALREADY SAID. Before any of this, the grid drew with hard aliasing: lines thickening, thinning and dropping out row to row, reading as an uneven pitch. That is not the asset — measured out of the shipped GLB, all 361 floor quads and all 220 quads on each wall plate are 0.006 m wide and the floor plate spans 4.506 m on both axes, i.e. 18 cells plus one line width, so the geometry is exact. It was pixel-centre quantisation, and `taa` fixed it. Turning TAA on then revealed the SECOND defect underneath, which is the one still open: correctly resolved, a sub-pixel line can only be as bright as its coverage, so the grid went from harsh-and-uneven to even-and-too-faint. Anti-aliasing cannot add energy that the geometry never had. That is what `lineRgb` is here to buy back, and why the real fix is wider lines rather than any setting in this file.
//
// THE REAL FIX IS BLOCKED. Widening the quads means regenerating the plates, and `scripts/add-shell-grid.mts` — pass 5 of `build:room`, still named in package.json — is NOT IN THE TREE: not on disk, not in `git ls-files`, not ignored. `npm run build:room` cannot run until it is rewritten, so the grid geometry is frozen at 6 mm and everything below is working around that. The permanent answers, in order of how well they end: rewrite the generator and widen the lines; bind Filament's `setSampleCount` through `patches/react-native-filament+1.11.0.patch` (the route `pickEntityWithDepth` already took) for real MSAA; or a procedural `.mat` shader taking its width from `fwidth()`, which is the only one that is correct at every distance and is blocked on `matc` not being installed.
export const GRID_TUNING = {
  // Wall grids OFF. They are the worst case for all of the above — a wall seen near edge-on compresses its 0.25 m pitch into a few pixels and the plate reads as a dense band rather than a lattice — and they are noise while the floor's legibility is the thing being judged. Floor-only keeps one variable on screen. Turning this back on restores the shipped behaviour exactly: every wall the camera can see lights up during a wall placement, not only the wall being dressed.
  wallGrid: false,

  // Temporal anti-aliasing. Jitters the projection per frame and accumulates, so a line that misses the pixel centre this frame hits it two frames later and resolves to a partial grey instead of vanishing. That is what evened out the pitch — and it is also what made the grid too faint to read, for the reason in the header: resolved honestly, a sub-pixel line cannot be brighter than its coverage.
  //
  // DEFAULTED OFF, which is the shipped behaviour and the state this was backed out to on device. Turning it on reproduces the even-but-faint look exactly; it is worth pairing with `fxaa: false` and a brighter `lineRgb` before judging it, since all three were confounded on the first attempt. Its own cost, independent of the grid, is ghosting while the camera glides — ORBIT.smoothingTau keeps it moving for ~0.2 s after every gesture and every HUD button — so if furniture edges or the drag ghost trail, this is the suspect.
  taa: false,

  // FXAA. Filament's default, so this is the first time the render path has stated it either way, and it has been on unopposed all along. It is a post-process edge filter and cannot recover a line that was never rasterised, so it has never done anything for the grid — what it does do is soften the whole image, and with `taa` on it is a second blur applied over the TAA resolve. Turn it off first if the room reads SOFT rather than smeared: soft is this, smeared is TAA.
  fxaa: true,

  // The grid lines' colour, and the one knob that fights faintness directly. Raising it toward white does not make a sub-pixel line cover more of its pixel, it only makes the fraction it does cover brighter — so this trades against the reason the value is grey in the first place: a near-white line is stark on a dark floor and nearly gone on a pale one, where a mid grey reads much the same against both. Try the floor finishes at both ends of that range before settling anywhere near 1.0.
  lineRgb: [0.72, 0.72, 0.72] as [number, number, number],
} as const;
