// GENERATED by scripts/gen-thumbs.mjs - do not edit by hand.
// Run: npm run gen:thumbs

import type { ClusterThumbMap, ThumbMap, ThumbSet } from "@/src/game/core/type";

export const thumbnail = { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/DALFRED.png") } satisfies ThumbSet;

export const thumbs = {
  "cap107675": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/seat_cap107675.png") },
  "circleDown": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/base_circleDown.png") },
  "circleUpp": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/base_circleUpp.png") },
  "leg": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/base_leg.png") },
  "pole": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/seat_pole.png") },
  "ringRail": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/base_ringRail.png") },
  "screw100212": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/base_screw100212.png") },
  "screw105251": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/base_screw105251.png") },
  "screw105298": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/base_screw105298.png") },
  "screw108443": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/seat_screw108443.png") },
  "seat": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/seat_seat.png") },
  "seatPlate": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/seat_seatPlate.png") },
  "supportPin": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/parts/base_supportPin.png") },
} as ThumbMap;

export const clusterThumbs = {
  "base": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/clusters/base.png") },
  "seat": { light: require("../../../../assets/thumbnails/furnitures/DALFRED/light/clusters/seat.png") },
} as ClusterThumbMap;
