// Presentation for avatar-recommendation. Only styling lives here — no state, no data, no handlers.

import { StyleSheet } from "react-native";
import { RADIUS, SPACE, TYPE } from "@/src/game/ui/theme";
import type { Theme } from "@/src/game/ui/theme";

export const makeStyles = (t: Theme) =>
  StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: t.bg,
      paddingHorizontal: 38,
      paddingVertical: 18,
    },
    header: {
      position: "absolute",
      right: 42,
      top: 18,
      zIndex: 10,
      flexDirection: "row",
      gap: 18,
    },
    navButton: {
      width: 56,
      height: 44,
      alignItems: "center",
      justifyContent: "center",
    },
    navText: {
      color: t.text,
      fontSize: 42,
      fontWeight: "900",
      lineHeight: 42,
    },
    recommendationLayout: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 34,
      paddingBottom: 66,
      paddingRight: 54,
    },
    audioButton: {
      alignSelf: "flex-start",
      flexShrink: 0,
      marginTop: 42,
    },
    modeCard: {
      width: 190,
      height: 260,
      alignItems: "center",
      justifyContent: "center",
      borderColor: t.border,
      borderRadius: 8,
      borderWidth: 2,
      backgroundColor: t.surface,
      gap: SPACE.sm,
      padding: 14,
    },
    modeCardRecommended: {
      borderColor: t.success,
      borderWidth: 3,
      backgroundColor: t.surfaceRaised,
    },
    avatarCircle: {
      width: 112,
      height: 112,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 56,
    },
    avatarImage: {
      width: 82,
      height: 82,
      borderRadius: 22,
    },
    recommendedBadge: {
      position: "absolute",
      top: 10,
      right: 10,
      borderRadius: 8,
      backgroundColor: t.success,
      paddingHorizontal: SPACE.sm,
      paddingVertical: SPACE.xs,
    },
    recommendedBadgeText: {
      color: t.onSuccess,
      fontSize: 9,
      fontWeight: "900",
    },
    modeTitle: {
      color: t.text,
      fontSize: 21,
      fontWeight: "900",
      textAlign: "center",
    },
    avatarName: {
      color: t.textDim,
      fontSize: 14,
      fontWeight: "800",
      textAlign: "center",
    },
    recommendationCopy: {
      flex: 1,
      minWidth: 0,
      gap: 7,
    },
    title: {
      color: t.text,
      fontSize: 26,
      fontWeight: "900",
      lineHeight: 31,
    },
    avatarLine: {
      color: t.text,
      fontSize: 16,
      fontWeight: "900",
    },
    personalityLine: {
      color: t.text,
      fontSize: 15,
      fontWeight: "800",
    },
    explanation: {
      color: t.textDim,
      fontSize: 13,
      fontWeight: "700",
      lineHeight: 18,
    },
    sloganLine: {
      color: t.success,
      fontSize: 14,
      fontWeight: "800",
      lineHeight: 18,
    },
    bulletList: {
      gap: 5,
    },
    bulletRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
    },
    bulletDot: {
      width: 9,
      height: 9,
      borderRadius: 5,
      backgroundColor: t.text,
    },
    bulletText: {
      flex: 1,
      color: t.text,
      fontSize: 13,
      fontWeight: "700",
    },
    modeTabs: {
      position: "absolute",
      left: 38,
      right: 38,
      bottom: 18,
      height: 56,
      flexDirection: "row",
      gap: SPACE.sm,
    },
    modeTab: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      borderColor: t.border,
      borderRadius: 8,
      borderWidth: 2,
      backgroundColor: t.surface,
      paddingHorizontal: SPACE.sm,
      paddingVertical: 5,
    },
    modeTabSelected: {
      borderColor: t.accent,
      borderWidth: 3,
      backgroundColor: t.surfaceRaised,
    },
    modeTabText: {
      ...TYPE.label,
      color: t.text,
      fontWeight: "900",
      textAlign: "center",
    },
    modeTabTextSelected: {
      color: t.accent,
    },
    modeTabRecommended: {
      color: t.success,
      fontSize: 9,
      fontWeight: "900",
      marginTop: 1,
    },
    saveErrorText: {
      ...TYPE.labelSm,
      color: t.danger,
    },
    dimOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.scrim,
    },
    highlightedPopup: {
      position: "absolute",
      right: 92,
      bottom: 58,
      width: 620,
      minHeight: 142,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      borderColor: t.gold,
      borderRadius: 28,
      borderWidth: 3,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.26,
      shadowRadius: 16,
    },
    noteCopy: {
      flex: 1,
      borderRadius: RADIUS.panel,
      backgroundColor: t.surface,
      paddingHorizontal: 20,
      paddingVertical: SPACE.lg,
    },
    noteTitle: {
      color: t.text,
      fontSize: 21,
      fontWeight: "900",
      marginBottom: 5,
    },
    noteText: {
      color: t.text,
      fontSize: 14,
      fontWeight: "700",
      lineHeight: 19,
    },
    taskActions: {
      flexDirection: "row",
      gap: 10,
      marginTop: SPACE.md,
    },
    smallMascotCircle: {
      width: 88,
      height: 88,
      alignItems: "center",
      justifyContent: "center",
      borderColor: t.gold,
      borderRadius: 44,
      borderWidth: 1,
      backgroundColor: t.surface,
      marginLeft: -8,
    },
    smallMascot: {
      width: 62,
      height: 62,
      borderRadius: 18,
    },
  });
